### ISSUE TITLE
Should I store my files in Teams or SharePoint? An understanding of behind the scene

### ISSUE THREAD

**Issue by veronicageek** [MicrosoftDocs/microsoft-365-community#134]
#### Article suggestion

Explain what's happening behind the scene when users are creating or uploading documents/files in a Team or Channel.

#### Submission Guidelines

With the push in using Microsoft Teams (_sometimes in a hurry due to the current circumstances_), I've heard so many times organisations asking this question, and I feel there's a need to clarify, and explain what happens to files, for example: 

- Where they are (really) stored, 
- Different ways to access them depending on how you feel comfortable (Teams or SPO),
- Are changes reflected in SPO if modifications are done in Teams,
- Who can access/see my files

**Comment by veronicageek** [comment]
@sympmarc - Happy for you to assign to me 🙂

**Comment by sympmarc** [comment]
Great idea! Now that we are in docs officially, let’s make sure we avoid duplication of existing content. Though in this case, I think your slant may be different than existing content. @JoanneHendrickson cal let us know.

**Comment by veronicageek** [comment]
I've only found this documentation, that's why I thought we could elaborate a bit:

https://support.microsoft.com/en-gb/office/file-storage-in-teams-df5cc0a5-d1bb-414c-8870-46c6eb76686a

**Comment by sympmarc** [comment]
That seems awfully minimal! I figured you’d done your research. :-)

**Comment by JoanneHendrickson** [comment]
Doing some checking for additional content -- will follow up shortly.  Thanks!

**Comment by veronicageek** [comment]
Hi @JoanneHendrickson, any news?

**Comment by JoanneHendrickson** [comment]
Hi @veronicageek   the only other one i found was this:  https://support.office.com/en-us/article/Should-I-save-files-to-OneDrive-or-SharePoint-d18d21a0-1f9f-4f6c-ac45-d52afa0a4a2e   , but I feel like it isn't specific enough.  Just pinged two other folks, and will get back to you later this morning.  But I think this idea definitely is worth pursuing.  Thanks!

**Comment by JoanneHendrickson** [comment]
Hey @veronicageek  -- let's go ahead and create a topic on this! Great idea.!
