### ISSUE TITLE
Information Architecture - List and Library "Limits"

### ISSUE THREAD

**Issue by sympmarc** [MicrosoftDocs/microsoft-365-community#135]
People are often confused by the supposed 5000 item "limit". I have complained about it many times. In reality, it isn't a "limit". There are ways to mitigate the issues with "large" lists:

* There’s no need to divide by 5000. It’s all about the use cases.
* The more realistic “limit” now is 20k items, but even that is a list view threshold. It’s always been a “list view threshold”, not a “limit”.
* When you build a list you expect to get larger than 20k items (especially on initial load), you should index the columns you expect to sort or filter by manually if you know. Remember that a view needs to be filtered first by a column which reduces the number of items below 5000, then any other column(s).
* The column limit is about how many lookup columns there are (and Person or Group columns are lookup columns). You can’t have more than 12 per view.
* You can have millions of items/docs in lists; it all depends what you want to do with them.

Let's frame all of this in a scenario illustrating what someone might encounter and how to think about solving their issues.

Tie ins: Power Apps. Power Automate

Related Content
* https://support.office.com/en-us/article/sharepoint-basics-large-lists-and-libraries-cf37b449-a2a7-4ef9-9f4d-aab826db5b30
* https://support.office.com/en-us/article/Manage-large-lists-and-libraries-in-SharePoint-B8588DAE-9387-48C2-9248-C24122F07C59
* https://support.office.com/en-us/article/Create-list-relationships-by-using-unique-and-lookup-columns-80A3E0A6-8016-41FB-AD09-8BF16D490632

**Comment by PatD** [comment]
Hey Marc - Please assign to me.

**Comment by sympmarc** [comment]
Thanks, @PatD. I had forgotten I added this one. :)

**Comment by PatD** [comment]
FYI, I'm about 80% complete on this one.

**Comment by PatD** [comment]
PR submitted. Definitely looking for some technical review on this one - I'm on GCC, so my Modern experience is about six months behind the rest of the world.
