### ISSUE TITLE
Error in licensing guidelines

### ISSUE THREAD

**Issue by akaskela** [MicrosoftDocs/microsoft-365-community#142]
#### Article issue

Article Title: Understanding Power Platform Licensing
Link: https://docs.microsoft.com/en-us/microsoft-365/community/powerplatformlicensingforcitizendeveloper

In the Licensing by Platform section, under "Run Unlimited Apps" – Per User/Per Month (e.g. US$ 40), there is a copy/paste error. The bullet point:
   * Sometimes referred to as the "Per App" Plan

is incorrect and should be deleted. This was probably copied from the "Run Single Apps" section and wasn't deleted.

**Comment by sympmarc** [comment]
@bigpix2000 - Can you handle this with your other updates?

**Comment by bigpix2000** [comment]
Yes and I thought I cleaned that one up before so indeed .... I should clean that one first and then deal with the bigger one which is to add the brand new licensing bit for RPA .... I need to get a use case for the latter.

**Comment by bigpix2000** [comment]
Fixed the quick issue above which turned out to be two bullet points wrong not just the one ... I  figured if it was a cut and paste issue that I thought was fixed then the other thing that was wrong was still wrong and indeed that was the case .... now fixed ... #141  will be in progress in the meantime thanks!

**Comment by bigpix2000** [comment]
I think I miss typed the fix for this one as related to 141 rather than fixing #142 ... I saw a merge go in for #143 which is related to this going to live so I believe we can close it also.  (I need a bigger keyboard as I get older )

**Comment by bigpix2000** [comment]
Checking @sympmarc if this is still open for the overall update or if the original problem was fixed (perhaps I neglected to include the issue when I did that work back then?)

**Comment by sympmarc** [comment]
Covered by the [Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/powerplatformlicensingforcitizendeveloper.md) article. Thanks, @bigpix2000!
