### ISSUE TITLE
Organizing Modern Communication Pages

### ISSUE THREAD

**Issue by pkbullock** [MicrosoftDocs/microsoft-365-community#151]
In light of a recent discussion around megamenus on twitter, it struck me that there isn't clear guidance on the options for organizing page content within modern communication site(s).

E.g. Multi-Site, Multiple pages, navigation including approaches, guidance

**Comment by sympmarc** [comment]
Good idea! I know @SusanHanley and @eemancini have thoughts on this.

**Comment by sympmarc** [comment]
@JoanneHendrickson - I think there may be some articles out there already or in the works?

**Comment by eemancini** [comment]
Happy to jump in on this one, @sympmarc!

**Comment by eemancini** [comment]
Closing this one for Community Content as Microsoft released this article: https://docs.microsoft.com/en-us/sharepoint/plan-navigation-modern-experience
