### ISSUE TITLE
CDS and Model-Driven Apps Naming Conventions

### ISSUE THREAD

**Issue by sympmarc** [MicrosoftDocs/microsoft-365-community#152]
#### Article suggestion

After a quick survey of the Power Community on Twitter, there don't seem to be any written standards for naming and other conventions around CDS and model-driven apps. Having some sort of guidelines for the community would be useful to ensure higher quality solutions.

**Comment by sympmarc** [comment]
Initial article stub: [CDS and Model-Driven Apps Standards and Naming Conventions](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/cds-and-model-driven-apps-standards-and-naming-conventions.md)

**Comment by pkbullock** [comment]
Hi Marc, I have a page, i'm working on for naming for SharePoint elements, just wondering if a glossary like page to consolidate, then other folks can add their tech/suggestions in. Depends on how much is written per area I guess. What do you think?

Ref #19

**Comment by sympmarc** [comment]
@pkbullock - I think the better practices for SharePoint are probably a bit different than for CDS, but since I can't find anything specific, I'm not sure! Let's keep the two ideas separate for now; we can merge later if it seems like it makes sense.
