### ISSUE TITLE
CDS - Related fields

### ISSUE THREAD

**Issue by KeithWhatling** [MicrosoftDocs/microsoft-365-community#156]
Related field logical names should be suffixed with id so a many - to - one relationship from an entity called measure to an entity called session would be pub_sessionid.

Relationship table names should be renamed to pub_measure_N1_session.

**Comment by sympmarc** [comment]
Added to [CDS and Model-Driven Apps Standards and Naming Conventions](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/cds-and-model-driven-apps-standards-and-naming-conventions.md) with some edits.

Feel free to edit the doc directly or continue to add ideas here.
