### ISSUE TITLE
Why SharePoint Training is important

### ISSUE THREAD

**Issue by veronicageek** [MicrosoftDocs/microsoft-365-community#158]
#### Article suggestion
Describe / give evidence as to why SharePoint Admins / Users training is important.

#### Submission Guidelines
From my experience, SharePoint is really misunderstood. Organisations (very) often neglect or underestimate the need for users training, throw users in the 'wild' and hope for the best, or simply don't use the platform because "too complex". 

I'd like to talk about:
- Mainly SharePoint as a platform, but **briefly** mention the integration with other apps
- Why it's beneficial for users (and/or admins) to have some SharePoint training (_daily tasks & efficiency_)
- This is _not_ a waste of time nor money

**Comment by veronicageek** [comment]
@sympmarc - Happy for you to assign to me.

**Comment by sympmarc** [comment]
@veronicageek I made some small edits and added a few Related Articles and Related Resources at the bottom.

**Comment by veronicageek** [comment]
No problem @sympmarc, thank you!

**Comment by veronicageek** [comment]
@JoanneHendrickson - FYI, the banner saying it's a community article is missing on the Live published version
