### ISSUE TITLE
How Do  Site Columns Become Managed Properties - Thus Available for Search?

### ISSUE THREAD

**Issue by sympmarc** [MicrosoftDocs/microsoft-365-community#168]
#### Article suggestion

From [this Twitter thread](https://twitter.com/darrel_miller/status/1255672761835556864) from Darrell Miller:

_If I create a site column based on a termset, will it create a managed property that can then be used by search so I can correlate search results to terms in my term store?_

If someone at Microsoft can be confused by this, it's very likely many other people are as well. The [article in a reply from Chris O'Brien](https://docs.microsoft.com/en-us/sharepoint/technical-reference/automatically-created-managed-properties-in-sharepoint) covers it. but does it make sense to a normal person?

**Comment by JimmyHang** [comment]
Hi @sympmarc, happy to be assigned this one as I'm actually using this in a couple of project couple with the awesome PnP Search Webparts here: https://microsoft-search.github.io/pnp-modern-search/

**Comment by sympmarc** [comment]
Thanks, @JimmyHang! I love those Web Parts. We use them in pretty much every project.

**Comment by JimmyHang** [comment]
Hi @sympmarc, PR for this article is submitted, I did use the template this time, ;)

Cheers

**Comment by sympmarc** [comment]
Sorry for the delay in getting this published, @JimmyHang. Working on it now and will get it out there later today...

**Comment by JimmyHang** [comment]
No problem @sympmarc, don't worry about it. 😁👍
