### ISSUE TITLE
Clarification on 3rd paragraph: Changes to Site Columns

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/microsoft-365-community#169]
Certain changes to Site Columns DO in fact propagate to Lists and Libraries where they are being used.

When editing the settings of a Site Column, there is a "Update Lists" section of the form.
    [screenshot?]
The "Update all list columns based on this site column?" is "Yes" by default but can be changed to "No" before saving changes; this will prevent changes to the Site Column settings from being applied to Lists/Libraries where the Site Column has been used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 960e66e1-4eaa-47f7-3b2e-0bf43bf18505
* Version Independent ID: 6f41c00e-31bc-217f-d5cc-91583322f2c4
* Content: [What is a site column?](https://docs.microsoft.com/en-us/microsoft-365/community/what-is-site-column)
* Content Source: [Community/what-is-site-column.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/live/Community/what-is-site-column.md)
* GitHub Login: @sympmarc

**Comment by sympmarc** [comment]
You are correct, Jim. Reading over that paragraph, I can't for the life of me remember what I was thinking. I've updated the article [Community/what-is-site-column.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/what-is-site-column.md) in the master branch; it will go live soon.
