### ISSUE TITLE
Basic Security Set Up for Microsoft 365

### ISSUE THREAD

**Issue by sympmarc** [MicrosoftDocs/microsoft-365-community#171]
#### Article suggestion

Many Microsoft 365 tenants are set up by non-technical folks these days, especially in small to medium sized businesses. The platform provides so much functionality, across so many different Admin Centers, etc., that is is incredibly overwhelming.

One of the primary concerns these folks have is how to ensure good security basics right off the bat. They don't really want to think about or understand all the ramifications: they just want things set up "right".

What are the basic security settings someone should identify and check as part of start up? Which of those settings is typically configured in a way that typically is not "right"?

Inspired by a chat with @juliemturner and a [Facebook thread](https://www.facebook.com/723919196/posts/10158312061719197/?d=n) from @TracyVDSchyff.

Articles like these are TMI:
* [Disable Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online?fbclid=IwAR0T15tlc0a56ukzO62YgCdvngMaSUhm6rEV2jEThldwMkqEiA_BMbjfZaA)
* [Enable or disable modern authentication for Outlook in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online?fbclid=IwAR0T15tlc0a56ukzO62YgCdvngMaSUhm6rEV2jEThldwMkqEiA_BMbjfZaA)

Can we build a good cheat sheet?

**Comment by helloitsliam** [comment]
Hey @sympmarc, I can take this one :-)

**Comment by sympmarc** [comment]
Awesome! Can't wait to see what you come up with, @helloitsliam.

**Comment by TracyVDSchyff** [comment]
Love this. Thank you @sympmarc , this is very needed!!!

**Comment by sympmarc** [comment]
I know, right, @TracyVDSchyff? If there are things you're learning as part of solving your recent issues, please add them here so we can fold them in. 

Now that you're here, do you have other ideas? If so, we'd love to have your expertise reflected in the repo! Feel free to grab an issue, contribute a blog post you've already written that may have larger appeal, add an article suggestion: whatever you can contribute.

**Comment by helloitsliam** [comment]
@TracyVDSchyff  if you do have anything to share or things that you found as you go through the tenant, let me know. Will be putting together a list of items that should be looked at with starter configuration, so could help :-)

**Comment by pamgreen-msft** [comment]
It will be great to hear the insights of real world use on what always has to be tweaked or what are the common scenarios small businesses have. We do have some guidance for small businesses already that's not the TMI articles cited above (geez @sympmarc you found the gnarliest articles! As you're putting together your checklist @helloitsliam, it would be great to reference what's already been covered, so we can keep adding on and not duplicate. Check out https://support.office.com/en-us/article/overview-of-microsoft-365-business-security-3274b159-a825-46d7-9421-7d6e209389d1 and anything else in the Small Biz content at https://support.office.com/en-us/smallbusiness that looks helpful. If it doesn't look like stuff you'd use with your customers, let us know and thanks for sharing your experience and knowledge in the Community Docs!

**Comment by PrasadKasireddy** [comment]
it's a great idea, I found the interesting Microsoft article that Top 10 ways to secure Microsoft 365 for business plans.
https://docs.microsoft.com/en-us/microsoft-365/admin/security-and-compliance/secure-your-business-data?view=o365-worldwide#10-protect-against-phishing-attacks-with-atp-safe-links

**Comment by bigpix2000** [comment]
I am marking my comment here for feedback on this as I am so very interested in the outcome here.  Looking forward to it!

**Comment by helloitsliam** [comment]
> It will be great to hear the insights of real world use on what always has to be tweaked or what are the common scenarios small businesses have. We do have some guidance for small businesses already that's not the TMI articles cited above (geez @sympmarc you found the gnarliest articles! As you're putting together your checklist @helloitsliam, it would be great to reference what's already been covered, so we can keep adding on and not duplicate. Check out https://support.office.com/en-us/article/overview-of-microsoft-365-business-security-3274b159-a825-46d7-9421-7d6e209389d1 and anything else in the Small Biz content at https://support.office.com/en-us/smallbusiness that looks helpful. If it doesn't look like stuff you'd use with your customers, let us know and thanks for sharing your experience and knowledge in the Community Docs!

Agreed @pamgreen-msft, makes sense to align with existing content as much as possible. :-)

**Comment by sympmarc** [comment]
Also see #21 and the article submitted to cover it.
