### ISSUE TITLE
Azure AD Groups Vs Office 365 Groups Vs SharePoint Groups

### ISSUE THREAD

**Issue by Harshagracy** [MicrosoftDocs/microsoft-365-community#173]
#### Article suggestion

**Azure AD Groups Vs Office 365 Groups Vs SharePoint Groups**

Needed in a perspective of 

- What is the benefit of each group  
- Use case scenario for each group
- Difference between them
- When to use and not to use these groups?
 E.g. when I need SharePoint search results to return data based on user permission, Office 365 groups does return results, but azure AD security group does. Such examples would be really helpful.

**Comment by sympmarc** [comment]
This is a great idea, Harsha. Are you interested in writing something or should I try to find someone to do it?

**Comment by Harshagracy** [comment]
Hi @sympmarc , Thanks for asking. I would love to, but honestly, I am still in the exploring stage for this area 😁. It would be better, if someone who has the practical knowledge could write this.

**Comment by sympmarc** [comment]
Totally fine - it's just as important to identify the gap as it is to fill it!

**Comment by pamgreen-msft** [comment]
Hi @Harshagracy , have you seen the article at https://docs.microsoft.com/microsoft-365/admin/create-groups/compare-groups? It may not cover Azure AD Groups as much as you're looking for but it gives a comparison of all the other types. @MikePlumleyMSFT Do you know if anything exisits already the meets Harsha's orginal need above?

**Comment by MikePlumleyMSFT** [comment]
That's that article that we have that compares groups, though not SharePoint groups.

**Comment by Harshagracy** [comment]
True... I agree.. But that article haven't covered the scenarios I mentioned like 
When to use and not to use these groups? 
Use case scenario for each group..

Infact I started with this article and created o365 group whereas I needed to create AD security group. 

That's where I need help from you all. :)

**Comment by ToddKlindt** [comment]
I'll grab this. I'll get something out there and you all can let me know what gaps I need to fill.

**Comment by sympmarc** [comment]
Thanks, @ToddKlindt!

**Comment by aaronrendell** [comment]
Hi @ToddKlindt, did you pick this up? I was going to submit an idea on this very topic, so would be happy to pickup or collaborate together?

**Comment by eemancini** [comment]
@aaronrendell I see Todd submitted the article in May and we forgot to close the issue. Feel free to open a PR for any amazing additions you may have :) https://docs.microsoft.com/en-us/microsoft-365/community/all-about-groups
