### ISSUE TITLE
Versioning on SharePoint 2019

### ISSUE THREAD

**Issue by ewyss-sword** [MicrosoftDocs/microsoft-365-community#175]
Versioning is enabled at creation on 2019 On premise document libraries (major versions up to 10)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6080b47a-816c-8bc8-94c0-506d040ae9bd
* Version Independent ID: c06f1880-827d-1d0b-c0fc-601432749411
* Content: [Versioning in SharePoint](https://docs.microsoft.com/en-us/microsoft-365/community/versioning-basics-best-practices#feedback)
* Content Source: [Community/versioning-basics-best-practices.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/live/Community/versioning-basics-best-practices.md)
* GitHub Login: @PatD

**Comment by PrasadKasireddy** [comment]
@ewyss-sword  - thanks for reporting typo, this is fixed with PR https://github.com/MicrosoftDocs/microsoft-365-community/pull/177, Team will merge soon
