### ISSUE TITLE
Update and Modernize Sadie Van Buren's SharePoint Maturity Model 

### ISSUE THREAD

**Issue by sympmarc** [MicrosoftDocs/microsoft-365-community#187]
#### Article suggestion

Sadie Van Buren's EXCELLENT work on the [SharePoint Maturity Model](https://www.uwebc.wisc.edu/IT/docs/2011-04-Presentation-SharePointMaturity-Burntsand.pdf) is an excellent source of ideas for articles for this repo. (There are other links to various iterations, but the original Web site is no more. The [Way Back Machine has it](https://web.archive.org/web/20170515104847/http://www.sharepointmaturity.com/home.aspx).)

I suggest we modernize the ideas into a set of articles and bring them up to the Microsoft 365 level. I will get the OK from Sadie. Anyone interested in starting this off: First thing to do IMO is to build an outline of articles titles here.

Also see:
- [SharePoint Adoption and Success: Navigating the Chasm of Despair](https://sympmarc.com/2011/08/10/sharepoint-adoption-and-success-navigating-the-chasm-of-despair/)

**Comment by sadalit** [comment]
@sympmarc let's do this!

**Comment by sympmarc** [comment]
Introduction article ready to go:  [The Microsoft 365 Maturity Model - Introduction](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/microsoft365-maturity-model—intro.md) 

Thinking through expansion of the model with @sadalit and @eemancini. Happy to have help!
