### ISSUE TITLE
Guidance for naming columns, sites, lists

### ISSUE THREAD

**Issue by pkbullock** [MicrosoftDocs/microsoft-365-community#19]
#### Article suggestion

This is more about best practice around naming artefacts in SharePoint, guidlines over naming, SharePoint has its quirks and good naming of lists, columns, sites etc can present a tidy and reduce technical issues later.

The article would help Citizen Devs structure things in clean ways to avoid issues later.

**Comment by pkbullock** [comment]
Happy for you to assign to me.

**Comment by pkbullock** [comment]
I have started this one, just need to check my fork since the move, and ill finish this one.

**Comment by sympmarc** [comment]
Hopefully the fork hasn't run away with the spoon.

Note that the restructuring may wreak a bit of havoc in your fork...

**Comment by pkbullock** [comment]
Think i may expand on this, seems my submission maybe a bit short...

**Comment by sympmarc** [comment]
Great to have something in place. I'll close this, and you can make edits later if you'd like.
