### ISSUE TITLE
SharePoint Online will let you manually create Indexes past 20,000 items

### ISSUE THREAD

**Issue by mrowell** [MicrosoftDocs/microsoft-365-community#190]
This page currently states that it's important to take create indexes early as `SharePoint Online won't let you create on past 20,000 items`

The official documentation says that automatic index creation stops at 20,000 items, and implies you can continue to manually create indexes. I tested sucessfully on a document library with 50K items. 

https://support.office.com/en-us/f1/topic/manage-large-lists-and-libraries-in-sharepoint-b8588dae-9387-48c2-9248-c24122f07c59#__bkmktimewindow?NS=SPOSTANDARD&Version=16
`Note: Automatic index creation when sorting in the modern experience is limited to lists and libraries with less than 20,000 items.
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7c49951-8871-c489-e4f3-81d845ebbce3
* Version Independent ID: c84959ec-3662-6963-00dc-5b3a0d9873c0
* Content: [Living Large with Large Lists and Large Libraries](https://docs.microsoft.com/en-us/microsoft-365/community/large-lists-large-libraries-in-sharepoint)
* Content Source: [Community/large-lists-large-libraries-in-SharePoint.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/live/Community/large-lists-large-libraries-in-SharePoint.md)
* GitHub Login: @PatD

**Comment by sympmarc** [comment]
@mrowell Thanks for the correction - sometimes it's hard to keep up with the changes. Would you like to make an edit to the article, or should we take care of it? We'd love to add you to our contributor list!

@PatD
