### ISSUE TITLE
Lifecycle of a Document

### ISSUE THREAD

**Issue by sympmarc** [MicrosoftDocs/microsoft-365-community#196]
### Article suggestion

Modern SharePoint coupled with Teams gives us new ways to think about the lifecycle of documents. An article that shows common document management scenarios would be of general interest.

Unfortunately, the fundamental architecture decision to use folders in Documents for Teams Files rather than something more sophisticated means that we can’t do rich metadata there. IMO, the Files in Teams should be used for more transitory work in progress files rather than files which are kept and have metadata applied. That makes life more complicated, but it just makes good sense.

**Comment by sympmarc** [comment]
Created a starting point in [Document Lifecycle Scenarios.](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/document-lifecycle-scenarios.md). I'd love your ideas or input!

**Comment by aaronrendell** [comment]
When I speak to customer I normally frame the concept of 'structured' vs. 'Unstructured data'. 

Structured being those formal Document Management sites which may use Content Types, Managed Meta-Data, Labels, Flows etc. 

Unstructured being OneDrive and Teams; day to day document collaboration, focusing on co-authoring and typically accessed through OneDrive Sync client.

There is a slide from MSFT that illustrates this 'inner loop' vs. 'Outer loop' (although it takes into account communication as well as document collaboration).

Is this inline with your thinking @sympmarc?  If so, I probably have some content that would certainly help.

**Comment by sympmarc** [comment]
In this article, I was thinking more about the way a document goes from a germ of an idea to some thing that has lasting value. **Sometimes** documents encapsulate a lifecycle like that, but it can also happen outside of documents altogether.

In other words, while we may use different technologies along the way, I wanted to focus on the state of the document just as much.

I should just finish this one. :)
