### ISSUE TITLE
Incomplete?

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/microsoft-365-community#197]
| To do this… | I need this permission… | |------------|------------------------| | View version history | Full Control, Contribute, Read | | Restore a previous version | Full Control, Contribute | | Delete a version | Full Control, Contribute | | Unpublish a version | Full Control, Contribute | | Recover deleted a deleted version | Full control and/or Contribute |

It seems this paragraph needs update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6080b47a-816c-8bc8-94c0-506d040ae9bd
* Version Independent ID: c06f1880-827d-1d0b-c0fc-601432749411
* Content: [Versioning in SharePoint](https://docs.microsoft.com/en-us/microsoft-365/community/versioning-basics-best-practices)
* Content Source: [Community/versioning-basics-best-practices.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/live/Community/versioning-basics-best-practices.md)
* GitHub Login: @PatD

**Comment by sympmarc** [comment]
@hwkwicre - Is there something specific you feel is incorrect?

**Comment by PrasadKasireddy** [comment]
@sympmarc  - table format is incorrect , However, in own repojectory the table format is showing correctly

![image](https://user-images.githubusercontent.com/11626905/85564242-b7c27b80-b64b-11ea-8c59-b2d893a31bb8.png)

**Comment by sympmarc** [comment]
Doh! I'm on it.

**Comment by sympmarc** [comment]
Fixed! Thanks, @JoanneHendrickson.
