### ISSUE TITLE
Explaining content type propagation

### ISSUE THREAD

**Issue by pkbullock** [MicrosoftDocs/microsoft-365-community#20]
#### Article suggestion

Explanation of how content types and site columns can be propagated through a site with sub sites and throughout a tenant.  Different approaches e.g. Enterprise Content Types, Site Collection level content types, how these can be setup and deployed. Pros/Cons for approaches allowing a decision to make based on their business scenario.

**Comment by pkbullock** [comment]
Happy for you to assign to me.

**Comment by JimmyHang** [comment]
Hi @sympmarc and @pkbullock, I'll be happy to take over this article if help is still needed. I'm doing research about this myself these days.. :)

**Comment by pkbullock** [comment]
Hey @JimmyHang go for it, since the changes and new features in this space I am out off date so would be beneficial to myself and I'm sure a few folks. Please shout if you need any help.  :-)

**Comment by sympmarc** [comment]
A lot has changed since you proposed it in 2019, too! I've done a session in the past about this topic, contrasting the CTH, Site Designs, and PnP Provisioning templates. Go for it, @JimmyHang.

**Comment by eemancini** [comment]
Looks like we missed formally assigning to you @JimmyHang. Updated! :) Looking forward to this one. Thanks so much for volunteering your time.

**Comment by JimmyHang** [comment]
Hi @sympmarc and @eemancini, this took some time, but I finally found the time to finnish this one. 

Cheers

**Comment by eemancini** [comment]
Thanks so much, @JimmyHang! We will review the article this week and let you know when it is being published.

**Comment by sympmarc** [comment]
@JimmyHang - The article you submitted is great, but it also overlaps quite a bit with existing Microsoft Docs:

* [Publish a content type from a content publishing hub](https://support.microsoft.com/en-us/office/publish-a-content-type-from-a-content-publishing-hub-58081155-118d-4e7a-9cc5-d43b5dbb7d02)
* [Create or customize a content type](https://docs.microsoft.com/en-us/sharepoint/create-customize-content-type)

(That said, those two articles are a bit out of date, and we'll let the Microsoft folks know.)

We've made some updates to help with the grammar and flow, but we think the really important value add for the article is the last sentence @pkbullock posted above: "Pros/Cons for approaches allowing a decision to make based on their business scenario." In other words, the WHY as opposed to just the HOW. You touch on the why, but I think you could add more.

Are you game to add more of that content?

**Comment by JimmyHang** [comment]
Hi Marc, yeah sure I'll add some samples to the pro/cons.

Cheers

**Comment by JimmyHang** [comment]
Hi @eemancini, @sympmarc shouldn't this be closed? :)

**Comment by sympmarc** [comment]
Right you are! Thanks.
