### ISSUE TITLE
Managing SharePoint security, a team perspective

### ISSUE THREAD

**Issue by pkbullock** [MicrosoftDocs/microsoft-365-community#21]
#### Article suggestion

How to setup SharePoint security groups, ad groups, site permissions, feature permissions, lock downs, aspects for each type of team may use, any pros/cons and best practices.

**Comment by pkbullock** [comment]
Happy for you to assign to me.

**Comment by pkbullock** [comment]
Please can you free this up for others to contribute on this subject.

**Comment by veronicageek** [comment]
@sympmarc @pkbullock - Happy to be assigned to this one if nobody is on it? 🙂

**Comment by sympmarc** [comment]
Done!
