### ISSUE TITLE
Access to on premises resources via a data gateway DOES NOT come with Office 365 Seeded

### ISSUE THREAD

**Issue by TheChaunz** [MicrosoftDocs/microsoft-365-community#220]
Great content and it provides a solid amount of clarity that I find myself having to explain frequently. That being said - Under Seeded Power Apps, it states: "Access to on premises resources via a data gateway" which is true for Dynamics seeded, but (to my understanding) NOT Office 365 Seeded. Additionally, the bullet is clarified as only being included with D365 under the "Seeded Power Automate" section. 

Am I missing a rather crucial point or can we make a correction to that bullet?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c843089f-7829-b8b4-3fcd-ef52bdc4f764
* Version Independent ID: a44c5d15-81cc-9d34-dd2e-8361f0852034
* Content: [Understanding Power Platform Licensing](https://docs.microsoft.com/en-us/microsoft-365/community/powerplatformlicensingforcitizendeveloper#power-apps)
* Content Source: [Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/live/Community/powerplatformlicensingforcitizendeveloper.md)
* GitHub Login: @bigpix2000

**Comment by bigpix2000** [comment]
We should make the change. Likely the older version of the license doc since corrected had it that way but confirming that the current doc is as you say. Easy to fix. Adding to the list to fix ASAP thanks for spotting it!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
