### ISSUE TITLE
Microsoft 365 Security Assessment Checklist

### ISSUE THREAD

**Issue by helloitsliam** [MicrosoftDocs/microsoft-365-community#224]
#### Article suggestion

When configuring a Microsoft 365 tenant, many services and features are available. Most of the time, Azure AD Connect is setup to Sync users and groups, and then the end-users just get to it. Some security capabilities may get enabled, and some may not. However, what predominantly happens is once it 'goes live' no-one really validates that the Security Controls and Capabilities enabled in the beginning are what is needed now. The idea is to outline the steps to take to assess the existing Microsoft 365 Tenant, places to check, configuration to review, and then discuss features such as regular access reviews. The goal is to provide almost a checklist of where to check, what to check and how to remediate.

**Outline:**
1. Performing Security Assessments and Reviews
2. Organizational Settings and Configuration
3. Authentication Settings and Configuration
4. Exchange Settings and Configuration
5. SharePoint Settings and Configuration
6. OneDrive Settings and Configuration
7. Teams Settings and Configuration
8. General Security Settings and Configuration
9. Organizational Settings and Configuration
10. Remediating Security Issues

**Comment by eemancini** [comment]
@sympmarc, is this resolved by https://docs.microsoft.com/en-us/microsoft-365/community/basic-security-set-up-for-microsoft-365?

**Comment by sympmarc** [comment]
Thanks for the article, @helloitsliam - closing this issue.
