### ISSUE TITLE
Site Mailbox is Deprecated But you Still List is as a Feature of a Team Site

### ISSUE THREAD

**Issue by SDillon001** [MicrosoftDocs/microsoft-365-community#234]
This article was written in May, 2020 but site mailboxes were deprecated in March of 2017. The docs are confusing enough, it would be great if the info was current and accurate. I just spent 10 minutes trying to setup a site mailbox I don't have.

[Important: The site mailbox feature in SharePoint is being deprecated beginning in March, 2017. This feature will be removed entirely in a future release. New SharePoint organizations no longer have access to the site mailbox feature. Existing SharePoint organizations can no longer create new site mailboxes.](https://support.microsoft.com/en-us/office/use-a-site-mailbox-to-collaborate-and-coordinate-team-email-57e361eb-39ef-400e-92de-f6408dab6b2b#:~:text=Important%3A%20The%20site%20mailbox%20feature,longer%20create%20new%20site%20mailboxes.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebb268a6-0b67-3867-5976-7dc5c74e2aaa
* Version Independent ID: fe8166b4-1ba5-6312-f52d-acc365de2eee
* Content: [Team Site vs. Communication Site -  Which one should I choose?](https://docs.microsoft.com/en-us/microsoft-365/community/team-site-or-communication-site)
* Content Source: [Community/team-site-or-communication-site.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/live/Community/team-site-or-communication-site.md)
* GitHub Login: @SusanHanley

**Comment by sympmarc** [comment]
@SDillon001 - When you create a Team Site, it creates an underlying Microsoft 365 Group which has a shared mailbox. For example, if I create a Team Site named "foo", by default I'll have a mailbox with the address foo@myorg.onmicrosoft.com.

**Comment by SDillon001** [comment]
@sympmarc thanks, but that's still not a 'site mailbox' as described in the linked article, which is also a feature listed under the 'Site Comparison' in the Team Site vs. Communication site article.

**Comment by sympmarc** [comment]
I know it's a subtle difference, but the article refers to a "shared mailbox", not a "site mailbox". Unfortunately, we suffer from Microsoft's naming changes over the years. Or am I missing something different?
