### ISSUE TITLE
Document Sets are Magic 🗂

### ISSUE THREAD

**Issue by PatD** [MicrosoftDocs/microsoft-365-community#238]
#### Article suggestion

Document Sets - and their embrace by your users - are a true sign of SharePoint maturity in your organization.

This article would discuss their creation, changes to them in Modern, and the relationship between metadata in the set vs. the document.  Should provide some sample use cases, and guidance on when/when not to use them.

**Comment by PatD** [comment]
I want to take this one, but lack clarity on whether Document Sets have a future in Modern. In my GCC tenant, it's sorta half-Classic, half-Modern. Nothing on the Road Map.  Anyone have any info about their future?

**Comment by sympmarc** [comment]
It's a fair question. Doc Sets have been partially modernized - which to me is not enough at all. In fact,. we lost some of the main benefits, like customizing the Welcome Page.

Let me see what I can find out - I love the things.

**Comment by PatD** [comment]
Consider me assigned! Will turn out a first draft in the next few weeks.

**Comment by sympmarc** [comment]
I asked in my MVP channels, but it's pre-Ignite, when all the MS folks are under the gun, so no useful replies. Looking forward to what you come up with!
