### ISSUE TITLE
Defining your Power Platform Environment Strategy

### ISSUE THREAD

**Issue by aaronrendell** [MicrosoftDocs/microsoft-365-community#244]
Hi.

I've been asked many times about 'Power Platform' governance; "how do I manage my Power Platform environments?".

The default environment that comes 'out of the box' is only suitable for 'Personal Productivity Apps', and additional environments are needed to support departmental or organisation wide Apps and Flows - however its often missed.

**Comment by aaronrendell** [comment]
I'll take this @sympmarc .I have a draft to submit. This would be a nice article to push before the Power Platform DLP one, that I'm drafting; follows on nicely.

**Comment by aaronrendell** [comment]
@sympmarc  - hi Marc, how do I add an image to an article? Upload to a folder and then include reference to the relative path in the doc?

**Comment by sympmarc** [comment]
That's correct. If you look in the repo here, you'll see a media directory at Community/media. Each article with images has a folder there named the same as the article, and the image are stored in that folder. Take a look at @eemancini's latest article as an example: [The Evolution of Company-wide Email Communication to SharePoint News](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/evolution-of-company-wide-email-communication-to-sharepoint-news.md).
