### ISSUE TITLE
Spelling issue

### ISSUE THREAD

**Issue by SergePoint** [MicrosoftDocs/microsoft-365-community#247]
In a few places in this article https://docs.microsoft.com/en-us/microsoft-365/community/auto-apply-retention-labels-in-office-365-using-content-types-and-metadata,  you mention: "site the retention label is published to had",  I guess you mean "add" and not "had" ?

**Comment by sympmarc** [comment]
I think @joannecklein's sentences say what she meant, but I can see the confusion. I'll have her take a look.

**Comment by joannecklein** [comment]
Hi @SergePoint - Thank you for pointing this out. The intention of those sentences was to say that within a week the retention labels would be applied based on the conditions specified on any sites the retention label had been published to. I've re-worded the sentences and hopefully they read clearer.
