### ISSUE TITLE
Comments on Should I store my files in Microsoft Teams or in SharePoint? An understanding of behind the scenes

### ISSUE THREAD

**Issue by sympmarc** [MicrosoftDocs/microsoft-365-community#270]
In the docs UI, there's an option to give a thumbs up or down and add a comment. Unfortunately, that content isn't available anywhere except through some @JoanneHendrickson hocus-pocus.

Here are the comments on [Should I store my files in Microsoft Teams or in SharePoint? An understanding of behind the scenes](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/should-I-store-my-files-in-Teams-or-SharePoint-An-understanding-of-behind-the-scenes.md):

> what happens the other way 'round? if someone is more comfortable working in sharepoint and uploads to the sharepoint library, does that automatically pull through to the teams site files section?

@veronicageek

**Comment by veronicageek** [comment]
@PatD - Whenever I do Teams training to customers, I always show them the relationship with SPO. Most of them are oblivious to the reality and only know Teams. I feel like clarity **needs** to be made. But then, they see you as "too technical".... 🤷🏻‍♀️  #sad

**Comment by veronicageek** [comment]
@sympmarc - Late for that one, but how do we answer to those comments? And then you can close the issues.

**Comment by sympmarc** [comment]
When we get comments like this, I think it's just useful to decide if the article needs any adjustment to help with the comment/question. Even though this happened a while ago, do you think any updates make sense? If not, feel free to close, or let me know you'd like me to.

**Comment by veronicageek** [comment]
@sympmarc - I believe the answer is in the "_How do I access my files?_" section, I also mention at the end that the changes are always reflected.

You can close the issue (I don't seem to have the right to do that) - Thanks.

**Comment by sympmarc** [comment]
Great. Closing for you...
