### ISSUE TITLE
Power Automate vs Logic Apps

### ISSUE THREAD

**Issue by pkbullock** [MicrosoftDocs/microsoft-365-community#285]
#### Article suggestion

- What they are?
- Highlight key differences between logic apps and power automate
- Use cases for choosing an approach

@sympmarc could you assign to me please? :-)

**Comment by veronicageek** [comment]
@pkbullock - Can't wait about this one. Hurry up! 😇

**Comment by pkbullock** [comment]
Lol- will start this one soon, I'm like a snail stuck on chewing gum 😂
