### ISSUE TITLE
Microsoft Learning Pathways Use Cases

### ISSUE THREAD

**Issue by eemancini** [MicrosoftDocs/microsoft-365-community#290]
#### Article suggestion

Sharing examples and scenarios for how M365 Learning Pathways can be used (business process documentation, in-context learning, new site owner training, new client support. etc)

**Comment by eemancini** [comment]
I'd be happy to take this one :)

**Comment by LuiseFreese** [comment]
If you like to, @eemancini - I'm happily offering help with that.

**Comment by eemancini** [comment]
@LuiseFreese, excellent! I will let you know when I post so you can add your phenomenal additions :)

**Comment by LuiseFreese** [comment]
YAY! love it :)
