### ISSUE TITLE
SharePoint and Office Groups update

### ISSUE THREAD

**Issue by LuiseFreese** [MicrosoftDocs/microsoft-365-community#298]
#### Article issue

https://github.com/MicrosoftDocs/microsoft-365-community/blob/live/Community/glossary.md#g

1. In the Section SharePoint groups, it says "library or library" which should most probably be "list or library" 
2. In the section Office groups it still has Office 365 groups although they were renamed in April 2020, details: https://techcommunity.microsoft.com/t5/microsoft-365-blog/office-365-groups-will-become-microsoft-365-groups/ba-p/1303601 and the description of the groups seems to need some clarification and touch-up. 

I am happy to make these changes. Just wanted to check upfront with the team before I submit a pull request.

**Comment by sympmarc** [comment]
Go for it, @LuiseFreese! It's the joy of open source!
