### ISSUE TITLE
Are 'Audiences' really enabled for News webpart?..

### ISSUE THREAD

**Issue by Gennady-G** [MicrosoftDocs/microsoft-365-community#307]
Greetings!

In this [article ](https://docs.microsoft.com/en-us/microsoft-365/community/evolution-of-company-wide-email-communication-to-sharepoint-news) You say that we "can enable audience targeting on the news web part to target your messages to the right people."
But if I change this switch I don't see any People Pickers:
![audience-2020-09-03_162945](https://user-images.githubusercontent.com/5569346/92115428-7399e700-ee03-11ea-9942-d4a38d6319c4.png)

Also enabled "Target Audiences" in "Site Pages" settings, but no result
Is this feature still in development, or I do something wrong?..

Best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27602f8a-1c77-7a3a-e585-94b496bf13fe
* Version Independent ID: 6c9c170f-fc07-0cd6-02f9-c72bbee11bd8
* Content: [The Evolution of Company-wide Email Communication to SharePoint News](https://docs.microsoft.com/en-us/microsoft-365/community/evolution-of-company-wide-email-communication-to-sharepoint-news)
* Content Source: [Community/evolution-of-company-wide-email-communication-to-sharepoint-news.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/live/Community/evolution-of-company-wide-email-communication-to-sharepoint-news.md)
* GitHub Login: @eemancini

**Comment by eemancini** [comment]
Hello @Gennady-G,

Wonder Laura has a great overview for how to do this. It looks like you enabled on the web part but you need to enable in the Site Pages library and tag the pages to the audiences: https://wonderlaura.com/2019/12/19/sharepoint-audience-targeting-its-back/#:~:text=%20Here%E2%80%99s%20how%20to%20start%20setting%20it%20up%3A,Enable%20audience%20targeting%2C%20and%20click%20OK.%20More%20

**Comment by Gennady-G** [comment]
@eemancini , aah, Ok! Thank You much, now I understand. So it works only with New SharePoint Groups, and every page has its own additional setting stored in 'Audience' column... It makes sense.

Best regards, Gennady
