### ISSUE TITLE
Missing 'provision bot' gif image

### ISSUE THREAD

**Issue by corecodes** [MicrosoftDocs/microsoft-365-community#314]
#### Article issue

Article Title: Should everyone create Teams? A Low Code Provisioning solution
 
Link: https://docs.microsoft.com/en-us/microsoft-365/community/should-everyone-create-teams#publish-our-bot--add-it-as-an-app-in-teams
 
In the 'Publish our Bot & add it as an App in Teams' section, the 'provision bot' gif image resource cannot be resolved. 
The relative path used is 'media/should-everyone-create-teams/provisionbot.gif'

**Comment by sympmarc** [comment]
Thanks for the heads up! We've been having some issues with GIFs - we'll get this sorted out.

cc: @LuiseFreese

**Comment by sympmarc** [comment]
Fixed!
