### ISSUE TITLE
Project Moca aka Outlook Spaces - yet another tool?

### ISSUE THREAD

**Issue by LuiseFreese** [MicrosoftDocs/microsoft-365-community#320]
#### Article suggestion

As Project Moca/Outlook Spaces is in preview, I would like to see and contribute to an article that provides some guidance about it. Which use cases does it serve, how does it integrate with other tools and services across Microsoft 365. I see a lot of people already forming their opinion in a direction of 'well, this is yet another tool' and will probably confuse a lot of users --> When to use what.

**Comment by sympmarc** [comment]
I haven't heard about this one. Is it firm enough to write something or is it still "in the lab"?

**Comment by LuiseFreese** [comment]
it's now officially in preview, a few months ago, MSFT accidentally leaked something, but then you didn't hear anything back from it... for reference: [Project Moca on Tech Community](https://techcommunity.microsoft.com/t5/outlook-blog/organize-content-your-way-with-the-preview-of-project-moca/ba-p/1620329). 

My article is about use cases and how Outlook Spaces integrates or correlates with other Tools and Services in M 365.

**Comment by LuiseFreese** [comment]
Uh-oh. Seems as if something went wrong 🥺🥺

**Comment by sympmarc** [comment]
Some of those errors (the ones on article-template.md) were my fault. There were a few for your article, but I've fixed them. Will read it later today...

**Comment by LuiseFreese** [comment]
anything I could clarify, @sympmarc ?

**Comment by sympmarc** [comment]
Went live tonight. Sorry for the delay!
