### ISSUE TITLE
Power Automate: Send SharePoint Files as Attachments

### ISSUE THREAD

**Issue by JimmyHang** [MicrosoftDocs/microsoft-365-community#326]
#### Article suggestion

Been working on a special scenario where I need to send a bunch of files in SharePoint as attachments in email. 
This will be a how-to article to achieve this. 

Happy for this to be asigned to me @sympmarc 

Cheers

**Comment by JimmyHang** [comment]
Done, pull request submitted.. ;)

**Comment by sympmarc** [comment]
But you didn't fill out the PR template! Bad Jimmy. :-)

Thanks, and I'll take a read today, if I can.

**Comment by sympmarc** [comment]
Actually, could you fix the alternate text on the image links? It's always harder for me to do it, since I'm not sure what they should be.

**Comment by JimmyHang** [comment]
Ouch, forgot about that one, I blame #MSIgnite, to much news..😁

**Comment by JimmyHang** [comment]
on it.. I'll submit a new PR

**Comment by JimmyHang** [comment]
Ouch, think I accidentally pushed changes to the PR template file also, can you ignore that change when you merge @sympmarc?

**Comment by sympmarc** [comment]
Checking it now!
