### ISSUE TITLE
Content Weight of Modern Communication SharePoint Sites

### ISSUE THREAD

**Issue by pkbullock** [MicrosoftDocs/microsoft-365-community#34]
#### Article suggestion

When designing communication sites, intranets for example some of the look books, the consideration of the amount of content required to implement the design.

Article could contain some planning considerations with an example of a look book page, with estimate amount of minimum content to achieve a design.

Sharing is caring.

**Comment by pkbullock** [comment]
I feel this one can be closed, i have noticed that the look books now indicate was added to making the design, thus this is no longer relevant.

**Comment by sympmarc** [comment]
Thanks, @pkbullock.
