### ISSUE TITLE
Confusing bullets in Flow licensing regarding CDS

### ISSUE THREAD

**Issue by briangre** [MicrosoftDocs/microsoft-365-community#342]
Under the flow licensing you will see this set of bullets:

- CDS included with Power Apps license
- 50 MB CDS DB Capacity per user when separate from Power Apps
- 200 MB CDS File Capacity per user when separate from Power Apps)

We need to clarify that first bullet. I am thinking the intention is that if you have a Power Apps license, that you get no additional CDS capacity with the flow license and if you do not have a Power Apps license, then you get the 50/200 allocations specified in the 2nd and 3rd bullets.

This bullet is confusing as a flow license provides access to premium connectors (of which CDS is one), but then it insinuates that you get CDS if you have a Power Apps license. 

This confusion exists in three sections:
- "Per User Plan" - Per User/Per Month (e.g. US $15)
- "Per User Plan with attended RPA" - Per User/Per Month (e/g/ US$40)
- "Per Flow Plan" - 5 Flows Per Month (e.g. US $500 and US $100 for each additional Flow.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c843089f-7829-b8b4-3fcd-ef52bdc4f764
* Version Independent ID: a44c5d15-81cc-9d34-dd2e-8361f0852034
* Content: [Understanding Power Platform Licensing](https://docs.microsoft.com/en-us/microsoft-365/community/powerplatformlicensingforcitizendeveloper#licensing-core-information)
* Content Source: [Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/live/Community/powerplatformlicensingforcitizendeveloper.md)
* Service: **power-platform**
* GitHub Login: @bigpix2000
* Microsoft Alias: **jhendr**

**Comment by sympmarc** [comment]
@bigpix2000 - Is this something you can help with?

**Comment by bigpix2000** [comment]
I definitely can and nothing that this Dataflex Oakdale stuff has made CDS questions perhaps the most asked Licensing question making the rounds.  This note also shows why it would have been a good idea to link to the Microsoft piece on this rathe than recreating tables with footnotes in MD form.  I agree it could be rewords to be cleared but I have to think about how to do that without making it too "busy"  as the bullets were an attempt to simplify the footnote packed table.  On it!

**Comment by briangre** [comment]
Thanks all! Looking forward to the updates.

**Comment by bigpix2000** [comment]
Looking at the bullets, we are probably not going to wait for Oakdale (Baby Skynet?  certainly not as cute as Baby Yoda) get a name   and we will be adding the unattended RPA with Flow added recently as well.

**Comment by LuiseFreese** [comment]
happy to help here - feeling qualified after my QnA Licensing session :-)  - is this ok for you, @sympmarc ?
