### ISSUE TITLE
It there a way to get around having two Single Line of Text columns for the same data?

### ISSUE THREAD

**Issue by edcuzz** [MicrosoftDocs/microsoft-365-community#353]
Thanks for this article. It is very helpful. I am curious if there is a way to get around having the Region duplicated as two Single Line of Text fields. One in Country and one in Region that contain the same data. Is it possible to use region as the source for the Region and have that reflected in country?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f4d29e9-64f8-9656-0678-8d67b3741d14
* Version Independent ID: 0ef6a487-4d7f-429a-a8cd-cfec53d6c990
* Content: [Working with Cascading Lists in SharePoint and Power Apps](https://docs.microsoft.com/en-us/microsoft-365/community/working-with-cascading-lists-in-sharepoint-and-powerapps)
* Content Source: [Community/working-with-cascading-lists-in-sharepoint-and-powerapps.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/live/Community/working-with-cascading-lists-in-sharepoint-and-powerapps.md)
* Service: **sharepoint-online**
* GitHub Login: @yllemo
* Microsoft Alias: **jhendr**

**Comment by sympmarc** [comment]
@edcuzz - I would use Lookup columns to relate the lists, like so:

### Country
- Title - Name of the country

### Region
- Title - Name of the Region
- Country - Lookup column to Country/Title


@yllemo
