### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by kevintaber** [MicrosoftDocs/microsoft-365-community#366]
Should you want to limit a user/group from editing within a Teams created SharePoint site, can you still do so within SharePoint and not have Teams overwrite the manually adjusted permission?

Example:

General channel has a group of staff that we don't want to make changes to the files/folders.

Just break inheritance and add a security group and adjust the permissions to read-only?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1d3e4e1-d09e-d2ab-7548-6e7f95dd1e03
* Version Independent ID: 4aed4d5a-0336-24fa-15eb-05d35e0c07b6
* Content: [Should I store my files in Microsoft Teams or in SharePoint? An understanding of behind the scenes](https://docs.microsoft.com/en-us/microsoft-365/community/should-i-store-my-files-in-teams-or-sharepoint-an-understanding-of-behind-the-scenes)
* Content Source: [Community/should-I-store-my-files-in-Teams-or-SharePoint-An-understanding-of-behind-the-scenes.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/live/Community/should-I-store-my-files-in-Teams-or-SharePoint-An-understanding-of-behind-the-scenes.md)
* Service: **msteams**
* GitHub Login: @veronicageek
* Microsoft Alias: **jhendr**

**Comment by CallumCrowley** [comment]
Thanks for raising the issue @kevintaber. To answer your question, if you have a some files or folders that you do not want any member of the Team to edit, then I would place these in a separate document library and give them read access by breaking inheritance on that one library. I would then add the library as an additional tab on the channel in Microsoft Teams.

**Comment by CallumCrowley** [comment]
@kevintaber did this help resolve your issue?
