### ISSUE TITLE
I see no "Actions" menu

### ISSUE THREAD

**Issue by devbenjamin** [MicrosoftDocs/microsoft-365-community#384]
I see no "Actions" menu. I am trying to access the SharePoint list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6080b47a-816c-8bc8-94c0-506d040ae9bd
* Version Independent ID: c06f1880-827d-1d0b-c0fc-601432749411
* Content: [Versioning in SharePoint](https://docs.microsoft.com/en-us/microsoft-365/community/versioning-basics-best-practices)
* Content Source: [Community/versioning-basics-best-practices.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/live/Community/versioning-basics-best-practices.md)
* Service: **sharepoint-online**
* GitHub Login: @PatD
* Microsoft Alias: **efrene**

**Comment by CallumCrowley** [comment]
Hi @devbenjamin 👋

The action menu is at the top of a list or document library when using the modern experience and contains the "New" button etc

![image](https://user-images.githubusercontent.com/58050310/126914751-0cbb3d2d-9d1b-47f1-9d02-21f1f2886323.png)
