### ISSUE TITLE
Highlight the Highlighted Content Web Part as the modern CQWP

### ISSUE THREAD

**Issue by PatD** [MicrosoftDocs/microsoft-365-community#388]
#### Article suggestion

I had been _bitter_ about the lack of Content Query Web Part in Modern, until I was introduced to the Highlighted Content Web Part. The Highlighted Content Web Part - paired with custom queries/KQL - is powerful stuff.

This article should:

- Describe what the Highlighted Content Web Part is
- Basics on using it
- Basics on Scope (Library/Site/Collection/etc)
- ...and a deep-dive into the KQL syntax with lots of concrete examples.  Like "_typing this KQL syntax will output these results_"
- Include managed metadata property examples. ( https://twitter.com/chambernate/status/1338606086140669954)

I want it to be something I'd bookmark and regularly reference because I can't ever remember the query syntax.

**Comment by sympmarc** [comment]
If you like the Highlighted Content Web Part, you'll _love_ the [PnP Modern Search Web Parts](https://microsoft-search.github.io/pnp-modern-search/)!

I'm guessing there are articles out there which cover the HCWP fairly well, but I'm not sure to what depth. Maybe @tomresing or @pamgreen-msft could point us to some of that content. That said, how to thread the needle with the existing search-based options would make a nice article. Understanding how things like KQL, tokens, scopes, managed properties, etc. all fit together to give us power would be very useful.

Are you interested in taking a crack at this @PatD or should I ferret someone out?

**Comment by PatD** [comment]
Please assign to me, happy to write it up.  If @tomresing or @pamgreen-msft have some resources to start with, please share here!

**Comment by tomresing** [comment]
[Use the highlighted content web part](https://support.microsoft.com/en-us/office/use-the-highlighted-content-web-part-e34199b0-ff1a-47fb-8f4d-dbcaed329efd) is the lead article. It's meant to cover the first three bullets in your list. If there are suggested changes or additions for that part, please let us know.
I don't see a lot of examples on KQL. There's [a limited set](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference#examples) in the server docs that are linked to from the first article. If you were to focus on building out some great examples and including community input like the twitter thread you reference, I think that would be a great complement to the existing docs. @wobba may have some KQL tips.

**Comment by wobba** [comment]
I'd love to contribute with samples. If someone has a list of useful scenarios to start with. Or I can come up with a pretty long list as well most likely. Knowing the schema properties is the hard part.

**Comment by sympmarc** [comment]
Adding @wobba for the samples. @PatD: want to coordinate?

**Comment by eemancini** [comment]
Hello @PatD, just checking in to see if you need any support on this article. Looking forward to seeing what you come up with :)

**Comment by PatD** [comment]
Yeah I think this one has simmered incomplete for long enough.  Heck of a year, but I can take this one on now that we're wrapping up 2021.

I don't want to just rehash [Microsoft's own documentation on this](https://support.microsoft.com/en-us/office/use-the-highlighted-content-web-part-e34199b0-ff1a-47fb-8f4d-dbcaed329efd) as it's already pretty thorough. Instead I think it should be more of a "Medium complexity KQL and CAML HCWP examples for site owners" thing.   

@wobba and @eemancini If you have real-world-ish samples/scenarios available I think that'd be hugely helpful!

**Comment by eemancini** [comment]
Sounds great, @PatD, and thank you for volunteering your time for this :) 

I think the most common (and my favorite) usage I have seen for HCWP is for Benefits documents on an Intranet Communication Site. So often there are tons of supporting documents for medical (hmo and ppo), dental, vision, wellness, life insurance, accidental death and dismemberment, etc. These benefits documents are changed each year at a very specific go-live for open enrollment but the structure of the Benefits site generally stays the same. There is a short period of time where the current year and future year documents need to both be accessible as well. Using metadata in the libraries to mark benefit type and year paired with the HCWP can make for incredibly easy transitions as the custom query just needs to be updated. 

Is that the type of scenario you are looking for?

**Comment by PatD** [comment]
Thanks @eemancini  - Yep that's exactly what I'm thinking of!  I think for documentation like this (intermediate level) there's value in pairing a story with an example. Anything like this is great.

**Comment by eemancini** [comment]
Agreed, @PatD! Helps form those mental models :)

Another example could be a training content scenario. In a previous organization the process to begin a contract with a vendor crossed multiple departments. The vendor qualification sat in the Quality team, the contract review was with Legal, and the vendor initiation was with Purchasing. These documents rightfully sat in each Communication Site but needed to be presented in a centralized location. There was a Site Column for document order which can only be supported through a custom query.

**Comment by PatD** [comment]
<img width="637" alt="image" src="https://user-images.githubusercontent.com/370735/142768072-e0c4ac41-3251-481c-83b0-7cbd1b09c425.png">

Doc is about 50% complete now.  Building lots of examples in a demo tenant.  

The Managed/Crawled property piece for complex filtering has a pretty significant learning curve on its own.  I relied heavily on this excellent Microsoft Community Docs writeup from @JimmyHang : [How Do Site Columns Become Managed Properties - Thus Available for Search](https://docs.microsoft.com/en-us/microsoft-365/community/how-do-site-columns-become-managed-properties-thus-available-for-search)

Not sure if this the first time a Community Doc was used to write _another_ Community Doc or not... but it is, we've reached full _Inception_.

**Comment by sympmarc** [comment]
An ouroboros!
![image](https://user-images.githubusercontent.com/1295627/142933930-3b8d22a6-5362-4ddf-b91d-43305ee678bf.png)

**Comment by PatD** [comment]
Progress:  Intro and example 1 complete.

This one is taking longer than I want - and I realized why.  The Highlighted Content Web Part appears simple at first, but all the good features of required their own learning paths.  I had to learn KQL, Managed/Crawled Properties, and CAML to be competent enough to write something of value for the Community Docs.

So that's what I'm framing the opening of this article as - not just "_Here are three examples_" but "_Here's what you'll need to learn first (using MS Docs and Comm Docs links) so you can understand these three examples._"

Flashes me back to using Content Query Web Parts and realizing "_Hey I can do something powerful here, I just have to learn XSLT first._"

**Comment by tomresing** [comment]
Thanks for the update. That sounds like a great intro. I remember trying to learn XSLT. There was so little available. I keep thinking CAML has gone the way of XSLT, until I get reminders like this. Is the highlighted content web part the only modern experience still relying on it?

**Comment by PatD** [comment]
Asking for help, frustrated.  I can't find documentation on writing CAML query for Highlighted Content Web Parts.  Microsoft's documentation implies it exists, but it is high level and seems skewed towards provisioning sites and creating content types.

Anyone have working examples of CAML for HCWPs that I can learn from?

**Comment by wobba** [comment]
Look at https://docs.microsoft.com/en-us/sharepoint/dev/schema/query schema and also this great caml builder plug-in https://github.com/andrei-markeev/camljs which has helped me a lot in the past.

**Comment by sympmarc** [comment]
@wobba - Your first link won't work for me. Maybe internal?

My bigger question is how you even use CAML. The HCWB clearly says you can, but then the **Query text** box indicates it wants KQL.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/1295627/146209663-634bee02-162b-48b2-b253-979a64413ae5.png">

**Comment by sympmarc** [comment]
Aha! Check out this article: https://support.microsoft.com/office/use-the-highlighted-content-web-part-e34199b0-ff1a-47fb-8f4d-dbcaed329efd#bkmk_customquery

_Select the source of the items you want to display. The source will determine the query language to use and the UI options you see:

This site, This site collection, and Select sites use KQL query strings. For more information on KQL, see the keyword-query-language-kql-syntax-reference

Document library and Pages library on this site uses CAML query strings. For more information on CAML, see the query schema for CAML._

**Comment by tomresing** [comment]
@sympmarc the first link from @wobba  doesn't resolve for me either. maybe it was missing the last part of the URL? https://docs.microsoft.com/en-us/sharepoint/dev/schema/query-schema does resolve and it's in a large section of developer docs on CAML.
Also, love how you're digging up the relevant info for @PatD to complete this. Clearly, this is an area that deserves this treatment!

**Comment by sympmarc** [comment]
@tomresing - Thanks for the right link. Hey, we're a community here: it's one for all and all for one!

**Comment by tomresing** [comment]
![3 musketeers](https://media.giphy.com/media/m6yXGH5hy4WzxtSGq5/giphy.gif)

**Comment by wobba** [comment]
https://docs.microsoft.com/en-us/sharepoint/dev/schema/query-schema?redirectedfrom=MSDN should work

**Comment by PatD** [comment]
Thank you @tomresing @wobba @sympmarc !  I've got a direction I can move in now.   

<img width="501" alt="image" src="https://user-images.githubusercontent.com/370735/146680628-0b0452af-ceab-4249-ac2a-f2ecdd21bc9c.png">

**Comment by sympmarc** [comment]
Thanks for this article, @PatD! I just ran through it and made some minor edits. It should be live soon.

**Comment by tomresing** [comment]
Let me know the URL when it's live. I'd like to share it and I don't see it yet.

**Comment by sympmarc** [comment]
@daisyfell just pushed to live (Thanks, @daisyfell!). 
https://docs.microsoft.com/en-us/microsoft-365/community/highlighted-content-web-part

**Comment by tomresing** [comment]
Thanks, @daisyfell!
