### ISSUE TITLE
Licensing Information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-community#391]
I noticed that the licensing section does not mention Business Premium. I think that this should be added. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: decdefc9-3082-1350-520c-ce226be74a6e
* Version Independent ID: 6457d5c9-87b0-bd1d-0a8e-7e5d9326851b
* Content: [Basic Security Set Up for Microsoft 365](https://docs.microsoft.com/en-us/microsoft-365/community/basic-security-set-up-for-microsoft-365)
* Content Source: [Community/basic-security-set-up-for-microsoft-365.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/live/Community/basic-security-set-up-for-microsoft-365.md)
* Service: **security**
* GitHub Login: @helloitsliam
* Microsoft Alias: **efrene**

**Comment by sympmarc** [comment]
@DeanGross - We welcome pull requests from smart people like you!

@helloitsliam- Want to check on this?

**Comment by helloitsliam** [comment]
> ## I noticed that the licensing section does not mention Business Premium. I think that this should be added.
> #### Document Details
> 
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
>     * ID: decdefc9-3082-1350-520c-ce226be74a6e
> 
>     * Version Independent ID: 6457d5c9-87b0-bd1d-0a8e-7e5d9326851b
> 
>     * Content: [Basic Security Set Up for Microsoft 365](https://docs.microsoft.com/en-us/microsoft-365/community/basic-security-set-up-for-microsoft-365)
> 
>     * Content Source: [Community/basic-security-set-up-for-microsoft-365.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/live/Community/basic-security-set-up-for-microsoft-365.md)
> 
>     * Service: **security**
> 
>     * GitHub Login: @helloitsliam
> 
>     * Microsoft Alias: **efrene**

What specifics do you mean? The only license piece really covers this "With all of the Microsoft 365 services, many-core security components come with the standard licensing. Features, such as the Security Defaults, are included in core licenses; however, most advanced Security capabilities are not. These features are either available as separate add-on licenses or bundled into the either the Enterprise Mobility + Security E3/A3/G3, Enterprise Mobility + Security E5/A5/G5, Microsoft 365 E3/A3/G3, Microsoft 365 E5/A5/G5, and Microsoft 365 E5/A5/G5 Security." Do you mean updating this?

**Comment by DeanGross** [comment]
@helloitsliam yes that is what I meant

**Comment by eemancini** [comment]
Hello @helloitsliam and @DeanGross, just checking in to see if there is any additional support you need or if we can close this issue. Thanks so much for both your contributions!

**Comment by helloitsliam** [comment]
> Hello @helloitsliam and @DeanGross, just checking in to see if there is any additional support you need or if we can close this issue. Thanks so much for both your contributions!

Thanks for checking in. For now this can be closed, as it was updated to the following: "**Enterprise Mobility + Security E3/A3/G3, Enterprise Mobility + Security E5/A5/G5, Microsoft 365 E3/A3/G3, Microsoft 365 E5/A5/G5, Microsoft 365 E5/A5/G5 Security, and Microsoft 365 Business Premium**"

We might need to review the licensing again with all the latest updates, but that can be done seperately. Thanks
