### ISSUE TITLE
Password Expriration

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/microsoft-365-community#392]
It would be helpful to add a link to this documentation also https://docs.microsoft.com/en-us/microsoft-365/admin/manage/set-password-expiration-policy?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: decdefc9-3082-1350-520c-ce226be74a6e
* Version Independent ID: 6457d5c9-87b0-bd1d-0a8e-7e5d9326851b
* Content: [Basic Security Set Up for Microsoft 365](https://docs.microsoft.com/en-us/microsoft-365/community/basic-security-set-up-for-microsoft-365)
* Content Source: [Community/basic-security-set-up-for-microsoft-365.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/live/Community/basic-security-set-up-for-microsoft-365.md)
* Service: **security**
* GitHub Login: @helloitsliam
* Microsoft Alias: **efrene**

**Comment by sympmarc** [comment]
@DeanGross - We welcome pull requests from smart people like you!

@helloitsliam- Want to check on this?

**Comment by CallumCrowley** [comment]
@sympmarc I have created PR #431 to resolve this.

**Comment by helloitsliam** [comment]
Hey @sympmarc, I actually created a different PR, that adds a missing license, and retains the original password expiration link plus the additional one. PR [432](https://github.com/MicrosoftDocs/microsoft-365-community/pull/432)

**Comment by CallumCrowley** [comment]
@helloitsliam thanks for adding the missing licence, PR #431 already has those links however.
