### ISSUE TITLE
Why Microsoft 365 adoption projects fail

### ISSUE THREAD

**Issue by LuiseFreese** [MicrosoftDocs/microsoft-365-community#395]
I would like to write an article why so many Microsoft 365 adoption projects fail. They focus on the WHAT and perhaps on the HOW of Microsoft 365 benefits rather than investigating corporate culture which is reflected in hierarchy, working methods, decision about tools. We heard before, that without cultural change we will only scratch the surface of what could M 365 do for us, but we never deep dive into core beliefs, mental models, structures and patterns that lead to "old world working behavior". Instead of fixing a broken system we try to fix users.

**Comment by kathyboilek** [comment]
Great idea and a suggestion about partnering  up with Emily. She has a
knack with understanding behaviors, etc.

**Comment by LuiseFreese** [comment]
great idea @kathyboilek - article is 80% ready now - but gladly to work as well with Emily on it. Right now this is a collaboration of @gezeitenbrand and me :-)

**Comment by sympmarc** [comment]
Also, be sure to check the relevant articles in MM4M365 to see what crossover there might be.
