### ISSUE TITLE
Designing User Interfaces for Diversity and Inclusion

### ISSUE THREAD

**Issue by sympmarc** [MicrosoftDocs/microsoft-365-community#398]
#### Article suggestion

@tomresing posted an [article on LinkedIn](https://www.linkedin.com/pulse/community-increases-diversity-inclusion-tom-resing/) today about how one person can make suggestions which lead to product documentation and wording which is better for everyone. It feels like we could have an article here which talks about how to build user interfaces and documentation which supports diversity and inclusion.

**Comment by LuiseFreese** [comment]
I would like to do that- if anyone wants to join, open to collaborate as well. 

I already have some ideas.

**Comment by Gezeitenbrand** [comment]
I would like to help you with that @LuiseFreese, scanning through some ideas already 🤘

**Comment by LuiseFreese** [comment]
happy to work with you!

**Comment by tomresing** [comment]
Let me know how I can help. I really like where this is going. Curious to hear the ideas!

**Comment by dcashpeterson** [comment]
If you still need assistance with this one I would be happy to add another set of eyes.

**Comment by sympmarc** [comment]
Three high-powered volunteers: can't wait to see what you come up with!

**Comment by Gezeitenbrand** [comment]
I just PR'ed an article for this and I'm looking forward to feedback :)
