### ISSUE TITLE
Microsoft Excel Multiple Signing, Document Versioning and Document Integrity

### ISSUE THREAD

**Issue by clarenznet** [MicrosoftDocs/microsoft-365-community#409]
#### Question

I am using office 365 and found a scenario I think office 365 should be able to solve. 
Consider I am an officer in a business and I have to issue out specific tools to at least 4 employees. I need them to accept receipt of the tools and digitally sign against an excel office 365 document I created online for future reference. I want to ensure document integrity once they sign until the day they have to handover the tools for clearance. Not having found a better solution online thought I should ask the developers on this platform. 

My thoughts were that a versioning system like GitHub will help to track any changes as a solution or a digital blockchain solution would easily solve the problem. 

I am looking forward to a solution that Bill Gates will definitely use. Thanks all.
#
#### Submission Guidelines
Thanks for your contribution! Sharing is caring.

**Comment by sympmarc** [comment]
@clarenznet - This is an interesting set of requirements, but it's pretty specific to your needs. I'd suggest posting in the [Microsoft Tech Community, SharePoint General hub](https://techcommunity.microsoft.com/t5/sharepoint/bd-p/SharePoint_General).

In this repo, we're trying to generate community-driven documents that help solve broad problems. I'm not saying your concept wouldn't be an excellent use case to document once you have it, but you won't get enough traction here to design that solution.
