### ISSUE TITLE
SharePoint Permissions vs. Office 365 Group Site Permissions

### ISSUE THREAD

**Issue by PatD** [MicrosoftDocs/microsoft-365-community#41]
#### Article suggestion

We've blown countless cycles on figuring out the relationship (or lack there-of) between old-world style SharePoint permissions, and the Members/Owners style permissions in a Group SPO site.  Feel like we can't be the only ones.

I think the target for this article might be _"Site Owner who's done On-Prem permission work and is thrown into the SPO lifestyle"_

This one could get wordy quickly - interested in suggestions for a narrower scope.

**Comment by PatD** [comment]
Assign to me please.

**Comment by sympmarc** [comment]
Done!

**Comment by PatD** [comment]
Just sent in the pull request for this one.

I welcome any and all suggestions/edits/feedback - I'm not a consultant, and only work in 1 farm, so my perspective might be a little limited.

**Comment by PatD** [comment]
Per Marc's March 2 request, this can either be closed - an article [exists](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/docs/basics/permission-model-diferences.md) or re-assigned.
