### ISSUE TITLE
Power Automate vs Logic Apps needs updating

### ISSUE THREAD

**Issue by Danielx64** [MicrosoftDocs/microsoft-365-community#422]
Just a small head up on this section:

> Did you know you can export from Power Automate into Azure Logic Apps? Yes, you can. If you are working with the Azure Portal it will require some knowledge of JSON, or for a friendlier experience using Visual Studio, check out the docs to consider your approach: https://docs.microsoft.com/azure/logic-apps/export-from-microsoft-flow-logic-app-template

That is no longer correct as this now applies:

> Important
> 
> Export to Logic Apps is unavailable for Power Automate flows created after August 2020. In October 2020, Power Automate standardized new flow creation on the OpenAPI 2.0 protocol. New flows based on this protocol are incompatible with Logic Apps workflows, so exporting these flows to Logic Apps was disabled. Instead, you must manually create logic apps for these flows.

Source: https://docs.microsoft.com/en-us/azure/logic-apps/export-from-microsoft-flow-logic-app-template

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3341b93-944b-b3b4-bdd2-3ef9df2a19d5
* Version Independent ID: 3ecd9b65-0dd5-6f08-b8cf-4766fbb6fa2d
* Content: [Power Automate vs Logic Apps](https://docs.microsoft.com/en-us/microsoft-365/community/power-automate-vs-logic-apps)
* Content Source: [Community/power-automate-vs-logic-apps.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/power-automate-vs-logic-apps.md)
* Service: **power-platform**
* GitHub Login: @pkbullock
* Microsoft Alias: **efrene**

**Comment by CallumCrowley** [comment]
Thanks for raising this. I've created a PR that should resolve the issue.
