### ISSUE TITLE
Default versioning

### ISSUE THREAD

**Issue by JeroenDerde** [MicrosoftDocs/microsoft-365-community#423]
For SharePoint Online, both Lists and Libraries now have versioning enabled by default. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6080b47a-816c-8bc8-94c0-506d040ae9bd
* Version Independent ID: c06f1880-827d-1d0b-c0fc-601432749411
* Content: [Versioning in SharePoint](https://docs.microsoft.com/en-us/microsoft-365/community/versioning-basics-best-practices)
* Content Source: [Community/versioning-basics-best-practices.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/versioning-basics-best-practices.md)
* Service: **sharepoint-online**
* GitHub Login: @PatD
* Microsoft Alias: **efrene**

**Comment by CallumCrowley** [comment]
This is resolved in PR #417 which is currently open.
