### ISSUE TITLE
Glossary Terms

### ISSUE THREAD

**Issue by sympmarc** [MicrosoftDocs/microsoft-365-community#44]
Strikethrough has been added to Glossary.md, but may need a definition.

~~Targeted Release~~
~~Standard Release~~
~~First Release~~

From Twitter:
* ~~Team Site~~
* ~~Tenant (and Farm)~~
* ~~Governance~~
* ~~Site Collection vs Site. Root site collection vs any other site collection.~~
* ~~Licensing (Kiosk, F1, E1, etc.)~~
* ~~Taxonomy~~
* List columns vs site columns vs managed metadata (term store).
* ~~Roll up~~
* ~~Out of the box~~
* Team's team. Team site. Group. - Explaining them is clunky. Any slick way to get them across is most welcome.
* ~~Hub, Home, SP start page (aka SP home)~~

**Comment by pkbullock** [comment]
I've seen something in docs for this...

- https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/content
- https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sites-servicedesc
- actually the entire service description section contains some of the blocks - https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-description 

ill post here if i find more....

**Comment by AnoopNagappan** [comment]
Hi friends,

Could you please guide me how to get context for other site collection... I need to fetch list from other site collection.

Any guiding docs or please feel free to share your thoughts

**Comment by sympmarc** [comment]
@AnoopNagappan - This is an issue about glossary terms. I think I answered your question above on Twitter.
