### ISSUE TITLE
Add information about SCA requirement to How Do Site Columns Become Managed Properties - Thus Available for Search

### ISSUE THREAD

**Issue by sympmarc** [MicrosoftDocs/microsoft-365-community#447]
#### Article suggestion

The current article [How Do Site Columns Become Managed Properties - Thus Available for Search](https://docs.microsoft.com/en-us/microsoft-365/community/how-do-site-columns-become-managed-properties-thus-available-for-search) covers the path from Site Column to Managed Property well. Given the recent (re)identification of a longstanding issue with getting Site Columns to become Crawled Properties, let's update this article to make it explicitly clear how to solve the problem.

I'll take a pass at it: suggestions and review welcomed from @wobba & @JimmyHang.

**Comment by sympmarc** [comment]
@wobba @JimmyHang - I've revised the article, adding an *Important* alert explaining the SCA thing. I'd appreciate any thoughts before we push it to live.

**Comment by wobba** [comment]
Do you have a link to review?

**Comment by JimmyHang** [comment]
Looks good for me @sympmarc, 👍

**Comment by wobba** [comment]
I'd like to be more specific.

```
If you are creating Site Columns in a modern Team Site (which has an associated Microsoft 365 Group), you must be a Site Collection Administrator explicitly for the crawled and managed properties to appear in the schema admin UX. The properties do exist and work for search, but makes it hard to do custom mapping.

This means adding yourself as an individual to the Site Collection Administrators. It is not sufficient to be an Owner of the Team Site (and thus of the underlying Microsoft 365 Group).
```

**Comment by sympmarc** [comment]
@wobba The sentence "The properties do exist and work for search, but makes it hard to do custom mapping" is basically irrelevant to the people who expect to see the Crawled Properties and don't. If they are there, but not visible, they aren't usable. I'm happy to add the sentence, but it won't help anyone - IMO, it just confuses things.

BTW, in one of the two tenants I provided in the email thread, we still don't see the CPs even after adding me as an SCA and re-indexing. In this case, I'm not an SP Admin (don't get me started), so I'm playing telephone with someone who is. Could the person who creates the Site Columns not being an SP Admin *also* prevent  the CPs from being visible?

**Comment by wobba** [comment]
@sympmarc I still think the explanation should be accurate. As the props are there and you can search against FooOWSTEXT and retrieve it. "For a cp to show in the admin UX add yourself as a sca" might be better. Cause you can map and all without it being in the UX.

**Comment by sympmarc** [comment]
@wobba AFAIK, you're the only person who knows about the XML file approach. :-) But no problem. I just made the change. 

Any idea on my other question above?

**Comment by sympmarc** [comment]
@wobba - It took a while, but the changes to the article just went live: [How Do Site Columns Become Managed Properties - Thus Available for Search](https://docs.microsoft.com/en-us/microsoft-365/community/how-do-site-columns-become-managed-properties-thus-available-for-search)
