### ISSUE TITLE
Wrong url in Notes

### ISSUE THREAD

**Issue by shawnpmiller** [MicrosoftDocs/microsoft-365-community#448]
In the notes section towards the top, you reference the url to access the nav. The url is listed as /layouts/ but should be /_layouts/
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 113ca464-7300-1bd0-8e66-7f6ab3839fb8
* Version Independent ID: 2b4fbf9c-27f3-4aec-3859-9065bb1f150b
* Content: [A Guided Tour Designed to Help You Select an Effective Navigation Strategy](https://docs.microsoft.com/en-us/microsoft-365/community/select-an-effective-navigation-strategy)
* Content Source: [Community/select-an-effective-navigation-strategy.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/select-an-effective-navigation-strategy.md)
* Service: **sharepoint-online**
* GitHub Login: @skaggej
* Microsoft Alias: **efrene**

**Comment by sympmarc** [comment]
Thanks for the fix, @shawnpmiller! I've made the change and it should be published soon.

We keep a log of folks who have contributed. If you'd like that recognition - for an underscore, even! - send me the link to your LinkedIn profile, as that's how we give credit.

**Comment by PrasadKasireddy** [comment]
@sympmarc -It seems that changes are not published, I will pick this
