### ISSUE TITLE
Flow and Premium Connector

### ISSUE THREAD

**Issue by MuSantana1** [MicrosoftDocs/microsoft-365-community#451]
If I'm reading it correctly, the following section states that "if the flow **does not use a premium connector** such as call Dataverse in the full production environment", then "**the cost of the flow must either be for each user or a per flow license is used so that all users of the list may be serviced by it**."

A common question is if a Flow is created for a SharePoint List and many users interact with that list, will there be a cost for all the users. The answer is if the flow **does not use a premium connector** such as call Dataverse in the full production environment and not the teams environment, **the cost of the flow must either be for each user or a per flow license is used so that all users of the list may be serviced by it**

Shouldn't it be "if the flow **uses** a premium connector" then "the cost of the flow must either be for each..."?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c843089f-7829-b8b4-3fcd-ef52bdc4f764
* Version Independent ID: a44c5d15-81cc-9d34-dd2e-8361f0852034
* Content: [Understanding Power Platform Licensing](https://docs.microsoft.com/en-nz/microsoft-365/community/powerplatformlicensingforcitizendeveloper#power-automate-per-flow-versus-per-user)
* Content Source: [Community/powerplatformlicensingforcitizendeveloper.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/powerplatformlicensingforcitizendeveloper.md)
* Service: **power-platform**
* GitHub Login: @bigpix2000
* Microsoft Alias: **efrene**

**Comment by bigpix2000** [comment]
@MuSantana1  I looked at one of my interim versions of this and you are correct as originally the statement was to say it was included and then a separate sentence to say the opposite.  in the streamline for the issue, it looks like it got mixed!   A quick fix should do it.  Thanks for looking at this closely and this is exactly what community is all about :)

**Comment by bigpix2000** [comment]
@sympmarc , can you assign this to me to fix?  its a quick one.  thanks! (noting that other areas in the post support the "fix" already and this appears to be the one item to clean)

**Comment by sympmarc** [comment]
@bigpix2000 - Did you make a change for this in your latest PR?

**Comment by bigpix2000** [comment]
Oh dear ... it looks like I missed this one ... for some reason it was not on my to do when I was clearing it.  It is still there.  Should I go to master to get it?  The fix is as they note (getting rid of a double negative) .... @sympmarc

**Comment by sympmarc** [comment]
If you're game - fix away!

**Comment by bigpix2000** [comment]
@sympmarc done .... and a bonus where I could also bring up the dev plan nuance which was not there when the note was made

**Comment by sympmarc** [comment]
Great! Thanks for taking care of it.
