### ISSUE TITLE
Adjusting PST Version Retention Policy 

### ISSUE THREAD

**Issue by rekamath** [MicrosoftDocs/microsoft-365-community#452]
We are introducing changes to the version retention policies for Outlook Data Files (PST File Type) and would like the documentation to reflect this:

The PST version retention policy changes are being introduced to address concerns around storage impact of PST versions and will ensure PST file versions no longer consume storage for extended periods. When PST files are uploaded on OneDrive for Business and SharePoint Online team site document libraries, Outlook updates PST files generating multiple versions which leads to storage being quickly consumed by the multiple versions of the PST file. With these changes the service will always retain a minimum of 30 day worth of PST versions that can be restored from.

As best practice we want to discourage uploading pst files on OneDrive for Business and SharePoint Online team site document libraries

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6080b47a-816c-8bc8-94c0-506d040ae9bd
* Version Independent ID: c06f1880-827d-1d0b-c0fc-601432749411
* Content: [Versioning in SharePoint](https://docs.microsoft.com/en-us/microsoft-365/community/versioning-basics-best-practices?source=docs)
* Content Source: [Community/versioning-basics-best-practices.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/versioning-basics-best-practices.md)
* Service: **sharepoint-online**
* GitHub Login: @PatD
* Microsoft Alias: **efrene**

**Comment by sympmarc** [comment]
@rekamath - This article doesn't mention PST files currently. Do you have a suggestion about where we should include this information? Feel free to do a pull request if you have specific edits.

**Comment by rekamath** [comment]
@sympmarc I would really like to include the PST version policy changes as a bullet point under the **"Best Practices and Versioning Trivia"** saying something like **"As best practice PST files should not be uploaded on OneDrive for Business and SharePoint Online team site document libraries due to the impact on storage. If PST files are uploaded the service will retain versions for 30 days."**

**Comment by rekamath** [comment]
@sympmarc I have no idea how to do a pull request so if you need me to do that could you please send me the instructions. Really appreciate your help here

**Comment by sympmarc** [comment]
@rekamath - I can take care of this for you, since it's a simple change. We like to give credit to people for updates, and we generally link to the person's LinkedIn profile. If you give that to me, I'll make sure you're on the list of contributors.

**Comment by rekamath** [comment]
Here is my linked  profile Reetu Kamath | LinkedIn<https://www.linkedin.com/in/reetukamath/>

**Comment by sympmarc** [comment]
Great, thanks. I've made the change, and it should be live later today, I expect.
