### ISSUE TITLE
Last paragraph needs cleanup / contradictory

### ISSUE THREAD

**Issue by duffymike** [MicrosoftDocs/microsoft-365-community#454]
Good article, but the last paragraph has contradictory statements. It looks like it was started and then first two sentences repeated with slight change being that Microsoft article agrees instead of disagrees. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 774d5574-4307-5a2d-5fde-020f7d4c0c40
* Version Independent ID: ae77d33a-e9c4-80d9-03f7-e93d1df26181
* Content: [Can Machine Learning be used to assign managed metadata attributes for items?](https://docs.microsoft.com/en-us/microsoft-365/community/machine-learning-and-managed-metadata)
* Content Source: [Community/machine-learning-and-managed-metadata.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/machine-learning-and-managed-metadata.md)
* Service: **machine-learning**
* GitHub Login: @bhall999
* Microsoft Alias: **efrene**

**Comment by sympmarc** [comment]
Thanks, @duffymike. I didn't see the contradiction, but there was definitely a repeat. Fixed!

Feel free to do a PR in the future if that's something you're comfortable with. In any case, this gets you on to the list of contributors for June!
