### ISSUE TITLE
Management of Content Competency requires explanation of "Putability"

### ISSUE THREAD

**Issue by modery** [MicrosoftDocs/microsoft-365-community#465]
The [Maturity Model for Microsoft 365 - Management of Content Competency](https://docs.microsoft.com/en-us/microsoft-365/community/microsoft365-maturity-model--management-of-content) article mentions the term "putability" 3 times, but offers no explanation what it actually means.

I remembered seeing it years ago, but couldn't figure out what it was. Best reference I found is in [this book](https://ptgmedia.pearsoncmg.com/images/9780735677821/samplepages/9780735677821.pdf), where it states
`You will sometimes hear the term putability, which, similar to the term findability, is the measure of how easy it is for a user to contribute high-quality, easily findable documents inside of SharePoint.`

I wasn't entirely sure if the same meaning is used here, so adding an issue rather than a suggested change

**Comment by sympmarc** [comment]
@modery - Sorry I missed this issue when you posted it. Would you like to do a PR yourself? Otherwise, I can certainly make an update. It probably makes sense to add this to the [Glossary](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/glossary.md) as well.

**Comment by modery** [comment]
Hi @sympmarc , it's better if someone else takes care of it. I would've done it, but wasn't entirely sure about the meaning and the right way to explain it

**Comment by sympmarc** [comment]
No worries, @modery. Just wanted to give you a chance to contribute. 

@SimonJHudson @SimonDoy Want to take a crack at this?

**Comment by SimonJHudson** [comment]
@modery Thanks for the issue; the use of 'Putability' is almost certainly down to me. Building on the quote you discovered, I (loosely) define it, as "The term 'putability' is the complement to the term 'findability'; it is a measure of how easy and obvious it is for content creators to know _where_ to store or create files or other information in a system. It is linked to elements of UI and UX design, leaning on information architecture, signposting and navigation".

Feel free to suggest improved wording, or we can just post it and await feedback (@sympmarc can you help me with that?)

**Comment by sympmarc** [comment]
I'll add that to the Glossary and link to it in the article. Seems good to me!

**Comment by SimonJHudson** [comment]
Splendid!

Simon Hudson
07735052905


Novia Works Ltd

Noviaconsulting.<https://noviaconsulting.co.uk/>co.uk


________________________________

**Comment by sympmarc** [comment]
Updates pushed live: https://docs.microsoft.com/en-us/microsoft-365/community/microsoft365-maturity-model--management-of-content
