### ISSUE TITLE
Managing External Guest in SharePoint vs Teams

### ISSUE THREAD

**Issue by JimmyHang** [MicrosoftDocs/microsoft-365-community#47]
External guest users are a bit scary, and there is big differences working with guest in SharePoint and Teams. This article will explain how it works and what to be aware of.

**Comment by JimmyHang** [comment]
Happy for you to assign to me @sympmarc 

Cheers

**Comment by sympmarc** [comment]
Done!

**Comment by JimmyHang** [comment]
Took me some time, but I finally found the time to complete this article, ;)

**Comment by sympmarc** [comment]
Thanks, @JimmyHang!
