### ISSUE TITLE
Need more detail on technical differences

### ISSUE THREAD

**Issue by FleurWilliamson** [MicrosoftDocs/microsoft-365-community#470]
I have come across other differences between Team sites and Communications Sites that should be listed on this page.  Eg Communication sites have the Multilanguage support that Team sites don't.  Also differences in Analytics.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebb268a6-0b67-3867-5976-7dc5c74e2aaa
* Version Independent ID: fe8166b4-1ba5-6312-f52d-acc365de2eee
* Content: [Team Site vs. Communication Site -  Which one should I choose?](https://docs.microsoft.com/en-us/microsoft-365/community/team-site-or-communication-site)
* Content Source: [Community/team-site-or-communication-site.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/team-site-or-communication-site.md)
* Service: **sharepoint-online**
* GitHub Login: @SusanHanley
* Microsoft Alias: **efrene**

**Comment by PrasadKasireddy** [comment]
Thanks for reporting @FleurWilliamson, we will update the doc

**Comment by PrasadKasireddy** [comment]
update the PR #https://github.com/MicrosoftDocs/microsoft-365-community/pull/471

**Comment by sympmarc** [comment]
In PR #471, @SusanHanley added the multilingual info. Please let us know if you think other info is missing.
