### ISSUE TITLE
Remove Understanding Power Platform Licensing Article

### ISSUE THREAD

**Issue by sympmarc** [MicrosoftDocs/microsoft-365-community#488]
#### Article issue

@bigpix2000 @LuiseFreese  
We've been asked to remove the [Understanding Power Platform Licensing](https://docs.microsoft.com/en-us/microsoft-365/community/powerplatformlicensingforcitizendeveloper) article. I'm going to do a PR this morning to take it out of the repo. I don't think we need to discuss this here, but I wanted to let you know.

@pamgreen-msft

**Comment by bigpix2000** [comment]
@sympmarc oh dear, that sounds major.  please let me know as soon as possible at the appropriate place. Thank you
