### ISSUE TITLE
Another small typo

### ISSUE THREAD

**Issue by HiltonGiesenow** [MicrosoftDocs/microsoft-365-community#495]
'co-located, in person working' should be 'co-located, **in-person** working' (hyphenated)
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db493db0-4524-2dec-dfc9-f708a5d063d1
* Version Independent ID: 2049ff98-f14b-2349-a03d-add5c07c3a39
* Content: [Maturity Model for Microsoft 365 – Collaboration Competency](https://docs.microsoft.com/en-us/microsoft-365/community/microsoft365-maturity-model--collaboration)
* Content Source: [Community/microsoft365-maturity-model--collaboration.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/microsoft365-maturity-model--collaboration.md)
* Product: **microsoft-365**
* GitHub Login: @sympmarc
* Microsoft Alias: **daisyfeller**

**Comment by sympmarc** [comment]
Thanks, @HiltonGiesenow. Fixing now. Feel free to do a PR when you see things like this if you want. If not, pointing them out is great.
