### ISSUE TITLE
Site column - Image (Thumbnail) - Need to know the Crawled or Managed property

### ISSUE THREAD

**Issue by anoopt** [MicrosoftDocs/microsoft-365-community#512]
Thank you for this article. It is very helpful.

Can you please let us know if a site column of the type `Image` will have a corresponding Crawled or a Managed property?

![image](https://user-images.githubusercontent.com/9694225/130764364-6f74f486-fc9c-41f5-bc7c-f4023a3bbda3.png)

I have done the following: 
- Followed the details mentioned in the article 
- Tried re-indexing the list (and site) a couple of times
- Waited for 24 hours
- Tried this in a couple of tenants

Please let me know if more information is needed on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fdf45bc-78d4-c713-e78b-bcd868e69a3a
* Version Independent ID: 4a4af3f5-3be9-db22-f7f1-6ecb81fdb1a3
* Content: [How Do Site Columns Become Managed Properties - Thus Available for Search?](https://docs.microsoft.com/en-us/microsoft-365/community/how-do-site-columns-become-managed-properties-thus-available-for-search)
* Content Source: [Community/how-do-site-columns-become-managed-properties-thus-available-for-search.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/how-do-site-columns-become-managed-properties-thus-available-for-search.md)
* Service: **search**
* GitHub Login: @JimmyHang
* Microsoft Alias: **daisyfeller**

**Comment by JimmyHang** [comment]
Hi Anoop, that's a very good question, I did a quick test on my end and nothings shows up in Search Admin, maybe I have to wait more. @wobba, @sympmarc any tips/experience to share? :)

**Comment by wobba** [comment]
Sounds about right. There is no crawled property emitted from `Image` columns today. I'm not sure of why this is but as it contains JSON like below, and if we added this into the index you would get recall on all the text in it like `thumbnail`, `fieldName`, `lists` etc. Which would not be a good search experience. I agree it makes sense as a non-searchable data, but by default all column values which emit an ows_column cp are included in the full-text index.

```json
{
    "type": "thumbnail",
    "fileName": "surprised.png",
    "nativeFile": {},
    "fieldName": "MyImage",
    "serverUrl": "https://tenant.sharepoint.com",
    "serverRelativeUrl": "/sites/foo/SiteAssets/Lists/6581dd9c-333e-47dd-bb11-6e934cac670a/surprised.png",
    "id": "ebd4e56a-2176-4a4f-866b-b16caed691fb"
}

```

**Comment by anoopt** [comment]
Thank you for the information @wobba.
