### ISSUE TITLE
The behindes of search and configuration

### ISSUE THREAD

**Issue by davemehr** [MicrosoftDocs/microsoft-365-community#513]
I can't find that much about the search yet. i'm happy to write some topics about the search, microsoft search and sharepoint search (aka modern search webparts).

Here are any topics, but perhaps it's better in more then one article, or what you mean?

- microsoft search
> answers
> data sources
> customizations

- sharepoint search
> use result sources incl query to help to find relevant results from different sites
> Use managed properties to map different crawled properties to use in one filters

**Comment by sympmarc** [comment]
@davemehr Thanks for volunteering! We have some content about search in the Maturity Model, but as you've noticed, not a lot else.

* [Maturity Model for Microsoft 365 - Search Competency](https://docs.microsoft.com/en-us/microsoft-365/community/microsoft365-maturity-model--search)
* [Introduction - The Principles of Search](https://docs.microsoft.com/en-us/microsoft-365/community/principles-of-search)

PnP Modern Search is awesome, and it make make more sense to contribute to their repo with specific [scenarios](https://microsoft-search.github.io/pnp-modern-search/scenarios/), etc. Several of us have been building out scenario articles there. That said, there probably should be a high level article here to introduce the idea and why they are so useful.

We do have an article already about [How Do Site Columns Become Managed Properties - Thus Available for Search](https://docs.microsoft.com/en-us/microsoft-365/community/how-do-site-columns-become-managed-properties-thus-available-for-search). That takes us a certain way down the road of search, but as you know, there's much more to it. If you have suggestions for improvement, etc., we'd love to hear them.

Given all that, what strikes your fancy?

**Comment by davemehr** [comment]
@sympmarc thanks for your feedback and your comments. Make sense that PnP Modern Search scenarios are saved in their own repo. 
I think, we can create new content about the Microsoft Search.

You mean an high level article about "When to us Microsoft Search and when SharePoint Search"?

The existing linked article are very good, it describes all about columns, we could now start there and continue with the result sources. 

I'm open for more inputs and comments, to create helpful content for the community.

**Comment by sympmarc** [comment]
"When to us Microsoft Search and when SharePoint Search" sounds like it would be useful. I was also thinking about "When to use PnP Modern Search". The titles are just examples, of course.

If there are thing about search you'd like to write about, please do! We try to avoid overlapping too much with the support articles (the "how"), and focus more on the "when" and "why".

**Comment by davemehr** [comment]
An high level article make sense, i plan to write them.

I consider about the "when" and "why" by search topics, so i think i can write one or another content.

**Comment by SimonJHudson** [comment]
I'd love to see something on embedding search in processes and applciations - not just adding a search box, but really leveraging search functions to improve processes.
A real world example: we have just gone live in our clinical application with a (Azure cognitive services) function that looks at a clinical message a doctor is writing and suggests published clinical guidance he/she could use to answer the question they were asking.
It would be great to see how best to integrate these from a UX point of view and how to balanceperfromance, cost and usability. for example.

**Comment by sympmarc** [comment]
Here are a few more sets of existing articles you might want to check for overlap:
* [Search experiences in SharePoint](https://docs.microsoft.com/en-us/sharepoint/get-started-with-modern-search-experience)
* [Microsoft Search](https://docs.microsoft.com/en-us/microsoftsearch/)

**Comment by eemancini** [comment]
Hello @davemehr, just checking in to see if you need any additional support on this article. Can't wait to see what you come up with :)
