### ISSUE TITLE
Internal names are limited to a specific length up to 255 Characters in SharePoint Online

### ISSUE THREAD

**Issue by coupalm** [MicrosoftDocs/microsoft-365-community#524]
This is true only for document libraries. For lists, internal names are limited to 32 Characters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4820cfd-6c16-cf3d-dafe-faebe9db24ca
* Version Independent ID: 041df04f-8b58-d8a3-82a0-bfb330a7c3c9
* Content: [SharePoint Naming Guidelines](https://docs.microsoft.com/en-us/microsoft-365/community/sharepoint-naming-guidelines)
* Content Source: [Community/sharepoint-naming-guidelines.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/sharepoint-naming-guidelines.md)
* Service: **sharepoint-online**
* GitHub Login: @pkbullock
* Microsoft Alias: **daisyfeller**

**Comment by pkbullock** [comment]
I will validate and update the article, thx @eemancini for hoghlighting

**Comment by eemancini** [comment]
Thanks so much, @pkbullock!
