### ISSUE TITLE
page text needs editing

### ISSUE THREAD

**Issue by brucelangston** [MicrosoftDocs/microsoft-365-community#528]
The first sentence of the article, "Power Automate and Azure Logic Apps are workflow services that can automate your processes business or system...," needs editing.  A comma after "processes" would help, but then the next part doesn't really fit.  Microsoft docs used to be impeccably edited.  Now, with offshore outsourcing, people who can speak English reasonably and communicate satisfactorily is most business or social situations are not adept enough for the standard of excellence I have come to know Microsoft can provide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3341b93-944b-b3b4-bdd2-3ef9df2a19d5
* Version Independent ID: 3ecd9b65-0dd5-6f08-b8cf-4766fbb6fa2d
* Content: [Power Automate vs Logic Apps](https://docs.microsoft.com/en-us/microsoft-365/community/power-automate-vs-logic-apps)
* Content Source: [Community/power-automate-vs-logic-apps.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/power-automate-vs-logic-apps.md)
* Service: **power-platform**
* GitHub Login: @pkbullock
* Microsoft Alias: **daisyfeller**

**Comment by eemancini** [comment]
Hello @brucelangston. Thanks so much for your help identifying some grammar edits to the articles. Microsoft Community Content is a community-run initiative, not outsourced, so all of this content is created by volunteers who are passionate about Microsoft 365. We appreciate your patience as we find the balance between getting content in front of people and ensuring it matches Microsoft standards. 

If you are interested in contributing, whether that is writing or providing edits like these, we would love to have your help. If you are new to GitHub the Sharing is Caring team runs a wonderful, free training session called "First Time Contributors" where they walk through the process to submit pull requests for edits just like this one: https://pnp.github.io/sharing-is-caring.

I will go ahead and make the edits you recommended. Let me know if you want to discuss anything further :)
