### ISSUE TITLE
Intranet Content Sources and Ideas

### ISSUE THREAD

**Issue by pkbullock** [MicrosoftDocs/microsoft-365-community#533]
#### Article suggestion

The idea comes from recent Viva connection projects where clients are struggling with what to write for a brand new intranet. This article suggestion would suggest ideas based on experience and observations from projects and common writing. 

So when your writing news, events, departments etc you have suggestions of content that could be informative and engaging. 

This is quite open so could invite others to contribute but I'm happy to get the ball rolling. 

I assume this doesn't clash with the writing surveys @eemancini is doing.

**Comment by eemancini** [comment]
Love the idea! My idea is more related to creating a course to support new Comm Docs authors so no clashing in sight :)

**Comment by pkbullock** [comment]
Once/If approved this issue can be closed :-)

**Comment by eemancini** [comment]
Thanks, @pkbullock! We will review shortly :)
