### ISSUE TITLE
Display permanently

### ISSUE THREAD

**Issue by CLBTraining** [MicrosoftDocs/microsoft-365-community#537]
Hi
Wonder if anyone can help.  I upload a lot of files to different Sharepoint sites and when its only two or less, I have to click the Circle Arrow key to see the progress bar on the right hand side.  Is there a view or way I can display it permanently on the right independent of how many files I upload?

Thanks from South Africa

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c057607-2ab2-d672-5eb2-85f3747a2cc3
* Version Independent ID: 007469e7-8a2a-f47a-6d95-f66b4c471e98
* Content: [Importing data into SharePoint](https://docs.microsoft.com/en-us/microsoft-365/community/importing-data)
* Content Source: [Community/importing-data.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/master/Community/importing-data.md)
* Service: **sharepoint-online**
* GitHub Login: @nyoung30
* Microsoft Alias: **daisyfeller**

**Comment by eemancini** [comment]
Hello @CLBTraining. This Issue list is for content related to the Microsoft Community Content. I recommend posting on [Tech Community](https://techcommunity.microsoft.com/t5/sharepoint/ct-p/SharePoint) for additional help. To my knowledge, there is no out of the box way to permanently display this upload progress bar.
