### ISSUE TITLE
Add in the link to the new governance risk and compliance competency

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/microsoft-365-community#575]
Add in a link to the new governance risk and compliance competency page
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13d0b11f-eb27-dc86-2441-66b92d1d820b
* Version Independent ID: 59a88ea9-f6c1-d719-e033-43b3ddd02c30
* Content: [Maturity Model for Microsoft 365 - Introduction](https://docs.microsoft.com/en-us/microsoft-365/community/microsoft365-maturity-model--intro)
* Content Source: [Community/microsoft365-maturity-model--intro.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/microsoft365-maturity-model--intro.md)
* Product: **microsoft-365**
* GitHub Login: @sympmarc
* Microsoft Alias: **daisyfeller**

**Comment by sympmarc** [comment]
Good catch! I'm on it.
