### ISSUE TITLE
Importing data into SharePoint

### ISSUE THREAD

**Issue by PatD** [MicrosoftDocs/microsoft-365-community#58]
#### Article suggestion

Site Owners should be ready to assist, and encourage, end-users with getting their existing stuff into SharePoint.  

Think it should be scoped to methods, not metadata/folder nuances.  Would like to see an article on the methods both front-end-center (dragging and dropping folders) and power-user focused (Excel-export to SharePoint?).

**Comment by nyoung30** [comment]
I'll help with this one.

**Comment by sympmarc** [comment]
Thanks, @nyoung30!

**Comment by nyoung30** [comment]
Hi @PatD 

[First draft](https://github.com/SharePoint/sp-usage-docs/blob/master/docs/basics/importing-data.md) complete. Review and provide feedback if you like.

Thanks.

Norm

**Comment by sympmarc** [comment]
I'm going through it and just adjusting some formatting, etc.

We may want to add some info about the [SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/introducing-the-sharepoint-migration-tool).

We have a spectrum of options here, from the drag and drop you start with to using third party migration tools.

**Comment by sympmarc** [comment]
And I should have said thank you for the contribution!

**Comment by sympmarc** [comment]
Suggestion from Francis Laurin:

_Using OneDrive sync to move lot of content. Found that Copy/Move To is unreliable for hundreds of files and folders. Also, SP Migration Tool to move from file share._

**Comment by nyoung30** [comment]
More good ideas. I'll add to the list.

Thanks.

**Comment by sympmarc** [comment]
Suggestion from Russell Gove:

_Using MS Access. we can pull data from sql server and pump it in to sharepoint lists._

**Comment by sympmarc** [comment]
Since this article is getting pretty long, I added a navigation table at the top.

**Comment by PatD** [comment]
@nyoung30 Good article, appreciate the screenshots!

**Comment by nyoung30** [comment]
The article is complete. @PatD can you please close the issue?

**Comment by sympmarc** [comment]
Thanks, @nyoung30!
