### ISSUE TITLE
Useful URLs for Your Users Using M365

### ISSUE THREAD

**Issue by PatD** [MicrosoftDocs/microsoft-365-community#588]
#### Article suggestion

Piggybacking on these two tweets and their high-quality replies:

[https://twitter.com/SwearPointJS/status/1493618618768105480](https://twitter.com/SwearPointJS/status/1493618618768105480)

[https://twitter.com/SwearPointJS/status/1427632730813124625](https://twitter.com/SwearPointJS/status/1427632730813124625)

...I'd like to suggest an article that covers URLs of value to Power Users and Site Owners.   Two focus points will be query string URL filtering, and shortcut URLs to provide easy access to products. 

I think even with the push towards installed-app Teamsification of everything M365, there's still a ton of features/value in providing URL feature awareness. I know `IsDLG=1` isn't coming back, but I fully support our `env=WebViewList` future.

**Comment by sympmarc** [comment]
Want to take a crack at it, @PatD?

**Comment by PatD** [comment]
I do!  Assign to me please.

**Comment by sympmarc** [comment]
Done! And thanks, as always.
