### ISSUE TITLE
Markdown table broken

### ISSUE THREAD

**Issue by chanakavp** [MicrosoftDocs/microsoft-365-community#593]
![image](https://user-images.githubusercontent.com/16893134/156832598-36fe7cd4-4e10-4efa-9e2f-5685a406c8c5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b113f1-d1a3-6ba3-524d-501e0bbef749
* Version Independent ID: 13b113f1-d1a3-6ba3-524d-501e0bbef749
* Content: [Advanced Highlighted Content Web Part](https://docs.microsoft.com/en-us/microsoft-365/community/highlighted-content-web-part)
* Content Source: [Community/highlighted-content-web-part.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/highlighted-content-web-part.md)
* Service: **sharepoint-online**
* GitHub Login: @PatD
* Microsoft Alias: **daisyfeller**

**Comment by sympmarc** [comment]
Thanks for pointing this out, @chanakavp. I've put in a fix and we should get it deployed soon.

I'll be adding you to the list of contributors: there's no contribution too small!

**Comment by chanakavp** [comment]
Dear @sympmarc,
I'm honoured. I depend on Microsoft docs a lot, so I'm really glad to have an opportunity to support it in any way I can.
