### ISSUE TITLE
Checklist for helping/working a  customer build out a new SharePoint site

### ISSUE THREAD

**Issue by PatD** [MicrosoftDocs/microsoft-365-community#62]
I (as an admin/developer/builder of SharePoint) keep a non-customer/project-specific checklist of tasks to perform before handing over the keys to someone in the business. 

Things like:
- Permissions configured?
- Customer has had training if needed?
- Hub site yes/no?
- Customer knows how to get support?
- etc

I propose creating this "Site Builder/Owner: New Site Checklist" as part of the Usage Docs.

**Comment by nyoung30** [comment]
I can help with this one.

**Comment by sympmarc** [comment]
Thanks, Norm!

**Comment by nyoung30** [comment]
@PatD is there anything else you add to the checklist?

**Comment by PatD** [comment]
Hey @nyoung30 - maybe these?

- List versioning is enabled if you've built the customer a custom List
- Libraries have versioning enabled (if On-prem)
- Connected to Content Type Hub if one is available at organization
- Customer knows all the tools they're getting (Site, Group, Team, etc)
- Logo graphic added
- Sanity-check: Has the customer been added as a Member/Owner before telling them the site is ready?
- If Owners, they're made aware of their powers ("You can delete this whole site collection")
- Left-side navigation has any extra Lists/Libraries added.  Even experienced site users shouldn't be expected to find content in Site Contents

I can't think of anything beyond this that isn't edge-case.  Thanks for taking this one!

**Comment by PatD** [comment]
Oh dang, I didn't even see that you contributed the .md file for this already.  My bad for missing that!

**Comment by nyoung30** [comment]
Version 1 of the article is complete. I'll be happy to revisit in the near future. @PatD can you please close the issue?

**Comment by sympmarc** [comment]
Thanks, @nyoung30. @PatD - if you'd like to add anything, feel free to create a new issue or add a PR.
