### ISSUE TITLE
To Do, Planner, Lists or Teams

### ISSUE THREAD

**Issue by Choci5** [MicrosoftDocs/microsoft-365-community#622]
Hi all,
I tried different ways to create task for more people, but I can't set that a person could finish only the tasks, that he has assigned. Anyone is able to complete every task all the time. Can you help me with this problem please?

**Comment by sympmarc** [comment]
@Choci5 - Is your question related to one of the articles here?

**Comment by CallumCrowley** [comment]
@Choci5 I think this question might be better placed on [Microsoft Answers](https://answers.microsoft.com/en-us/msoffice/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1) or on the [SharePoint Stack Exchange](https://sharepoint.stackexchange.com/). This issues list is related to problems found on Microsoft 365 Community articles.
