### ISSUE TITLE
s=03 parameter?

### ISSUE THREAD

**Issue by fs366e2spm** [MicrosoftDocs/microsoft-365-community#632]
Great article which explains a lot.

I recognize that Microsoft links often have ?s=03 as a parameter at the end.
Is there something known what s=03 is for?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac77ab44-dbe6-f6bc-951e-a7e6d44fb8aa
* Version Independent ID: ac77ab44-dbe6-f6bc-951e-a7e6d44fb8aa
* Content: [Query String URL Tricks for SharePoint and Microsoft 365](https://docs.microsoft.com/en-us/microsoft-365/community/query-string-url-tricks-sharepoint-m365?source=docs)
* Content Source: [Community/query-string-url-tricks-sharepoint-m365.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/query-string-url-tricks-sharepoint-m365.md)
* Service: **sharepoint-online**
* GitHub Login: @PatD
* Microsoft Alias: **daisyfeller**

**Comment by sympmarc** [comment]
@fs366e2spm - That's a good question. I can't recall ever having seen that on the query string. Do you have any examples you could share? 

cc: @PatD
