### ISSUE TITLE
#grammar

### ISSUE THREAD

**Issue by blb0004** [MicrosoftDocs/microsoft-365-community#633]
Change "the bast way" to "the best way".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efceafa2-4c75-9534-5826-8d6f13391c8b
* Version Independent ID: 41bbd300-95aa-6eac-fa8a-dbc735c94102
* Content: [Power Automate - Send SharePoint files as attachments](https://docs.microsoft.com/en-us/microsoft-365/community/power-automate-send-sharepoint-files-as-attachments)
* Content Source: [Community/power-automate-send-sharepoint-files-as-attachments.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/power-automate-send-sharepoint-files-as-attachments.md)
* Service: **power-platform**
* GitHub Login: @JimmyHang
* Microsoft Alias: **daisyfeller**

**Comment by sympmarc** [comment]
@blb0004 - Thanks for the fix!

**Comment by sympmarc** [comment]
Fixed in `main`.
