### ISSUE TITLE
Wrong info

### ISSUE THREAD

**Issue by TheRealDepso** [MicrosoftDocs/microsoft-365-community#663]
There is no difference between Microsoft 365 Groups and SharePoint Groups in the rights management of these 2 types. Only Microsoft 365 Groups apply for both.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebb268a6-0b67-3867-5976-7dc5c74e2aaa
* Version Independent ID: fe8166b4-1ba5-6312-f52d-acc365de2eee
* Content: [Team Site vs. Communication Site -  Which one should I choose?](https://docs.microsoft.com/en-us/microsoft-365/community/team-site-or-communication-site)
* Content Source: [Community/team-site-or-communication-site.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/team-site-or-communication-site.md)
* Service: **sharepoint-online**
* GitHub Login: @SusanHanley
* Microsoft Alias: **daisyfeller**

**Comment by CallumCrowley** [comment]
@TheRealDepso Communication sites are not connected to Microsoft 365 groups. This is what the documentation is trying to define.

**Comment by sympmarc** [comment]
@TheRealDepso - Since we haven't heard back from you, we'll close this issue. If you think there's a problem with the article, please feel free to open a new issue.
