### ISSUE TITLE
Obsolete

### ISSUE THREAD

**Issue by jaywinksthrive** [MicrosoftDocs/microsoft-365-community#679]
PNPProvisioningTemplate is no more.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f961736d-5c03-df0f-f9f5-2e91bfcde4b4
* Version Independent ID: 332b9f9a-8496-dd14-17f2-9ab0ccffd303
* Content: [Working with modern client-side pages using PnP PowerShell](https://docs.microsoft.com/en-us/microsoft-365/community/working-with-modern-clientside-pages-using-pnp-powershell)
* Content Source: [Community/working-with-modern-clientside-pages-using-pnp-powershell.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/working-with-modern-clientside-pages-using-pnp-powershell.md)
* Service: **sharepoint-online**
* GitHub Login: @JimmyHang
* Microsoft Alias: **daisyfeller**

**Comment by JimmyHang** [comment]
Thanks for the feedback, I'll check the sample code, then update the article..👍👍

**Comment by jaywinksthrive** [comment]
Exactly right, and all I was trying to point out. For a n00b like me, that info would be rather helpful.


Jay Winks
Senior Platform Engineer
 205-278-8125
***@***.***
