### ISSUE TITLE
Azure environment issue-Could not load file or assembly ‘Newtonsoft.Json,Version=10.0.0.0’

### ISSUE THREAD

**Issue by AnoopNagappan** [MicrosoftDocs/microsoft-365-community#70]
**Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' in Azure Functions**

After copying  "MicrosoftTeams" modules files into Azure Kudu environment and and tried to run the "Connect-MicrosoftTeams" and getting below error, 

                       ‘Could not load file or assembly ‘Newtonsoft.Json, Version=10.0.0.0’

![error](https://user-images.githubusercontent.com/40852965/73527344-ec356100-4438-11ea-933c-2d0f0a1ddab3.png)

tried downgrading to Newtonsoft.Json 9.0.1. But even then the error still persist.

https://stackoverflow.com/questions/47351068/could-not-load-file-or-assembly-newtonsoft-json-version-10-0-0-0-culture-neut

**Comment by pamgreen-msft** [comment]
Hi @AnoopNagappan , I think you may have the wrong repo for  your issue. This issue over in the Azure Functions repo looks related to your question: https://github.com/Azure/azure-functions-vs-build-sdk/issues/107

**Comment by sympmarc** [comment]
@AnoopNagappan I'm going to close this issue, since it does seem to fit more where @pamgreen-msft pointed you. If you are still having the issue and feel it belongs here, we can reopen it.

**Comment by shivashyavi** [comment]
Still having the same issue. Were you able to resolve the issue Anoop?
