### ISSUE TITLE
SharePoint Listview URL Filtering

### ISSUE THREAD

**Issue by sekaing** [MicrosoftDocs/microsoft-365-community#720]
Hello All, 

Could someone please explain to me if possible why MS chose to only allow the Equal (=) operator for filtering list view using URL query string in SharePoint Online?
For example, I can use the following URL to filter my listview: it will display all items with "numberColumn" having exactly "12" as value.

?useFiltersInViewXml=1&FilterField1=numberColumn&FilterValue1=12

But what should I do if I wanted to see all items having "numbercolumn" LessThan "12"?
People also need to display items with value that are GreaterThan, LessThan, Containing this OR that value.... 
How would they do that?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac77ab44-dbe6-f6bc-951e-a7e6d44fb8aa
* Version Independent ID: ac77ab44-dbe6-f6bc-951e-a7e6d44fb8aa
* Content: [Query String URL Tricks for SharePoint and Microsoft 365](https://docs.microsoft.com/en-us/microsoft-365/community/query-string-url-tricks-sharepoint-m365)
* Content Source: [Community/query-string-url-tricks-sharepoint-m365.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/query-string-url-tricks-sharepoint-m365.md)
* Service: **sharepoint-online**
* GitHub Login: @PatD
* Microsoft Alias: **daisyfeller**

**Comment by sekaing** [comment]
@sympmarc  
Thank you for your reply. 
I am aware of the view filters with create/edit a view.
What I am looking for is, as you mentioned, use the dynamic filtering on the fly. 
I created a command set extension. Once the user clicks on the command, it prompts for a value, and uses the entered value to filter the list on the fly.
I am puzzled that MS offered the url trick for an "=" operator only... If they can do it for "=", why can't they do the same for "<", or ">" or "contains", "endsWith"....

**Comment by sympmarc** [comment]
I think the use cases for those extra options would be less common. That said, you should propose the enhancement in the [SharePoint Feedback Hub](https://feedbackportal.microsoft.com/feedback/forum/06735c62-321c-ec11-b6e7-0022481f8472).
