### ISSUE TITLE
How to trigger the flow

### ISSUE THREAD

**Issue by tmsbrdrs** [MicrosoftDocs/microsoft-365-community#729]
I've built the flow exactly as you have it laid out and went to test. Exactly as laid out, there is no way to trigger this flow, verified through Power Automate. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efceafa2-4c75-9534-5826-8d6f13391c8b
* Version Independent ID: 41bbd300-95aa-6eac-fa8a-dbc735c94102
* Content: [Power Automate - Send SharePoint files as attachments](https://docs.microsoft.com/en-us/microsoft-365/community/power-automate-send-sharepoint-files-as-attachments)
* Content Source: [Community/power-automate-send-sharepoint-files-as-attachments.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/power-automate-send-sharepoint-files-as-attachments.md)
* Service: **power-platform**
* GitHub Login: @JimmyHang
* Microsoft Alias: **daisyfeller**

**Comment by JimmyHang** [comment]
Hi, 

Not sure about what you mean with you cannot trigger the flow? You should find it in the context menu of a file/folder then "Automate", please note that the logic in this example is created with a "Folder" in mind, if it' single files, then you might need to change some of the logic.

![image](https://user-images.githubusercontent.com/18226765/189129245-868d2d0f-0a44-4a94-805f-0c7c7c8b1961.png)


Cheers

**Comment by sympmarc** [comment]
@tmsbrdrs - Did @JimmyHang answer your question?
