### ISSUE TITLE
Working with modern clientside pages using PnP PowerShell

### ISSUE THREAD

**Issue by JimmyHang** [MicrosoftDocs/microsoft-365-community#73]
#### Article suggestion

Tips & Trick related to clientside pags using PnP PowerShell  

- Creating new pages
- Modifying webpart properties

Please assign this to me @sympmarc

**Comment by JimmyHang** [comment]
Article commited, ;)

**Comment by sympmarc** [comment]
Thanks, @JimmyHang. I'll probably be making some edits to bring it into line with the new structure we're working toward (but haven't documented yet).

**Comment by JimmyHang** [comment]
#awesome..
