### ISSUE TITLE
SharePoint Online versioning retention

### ISSUE THREAD

**Issue by natlims18** [MicrosoftDocs/microsoft-365-community#734]
Hi, how much retention time (number of days) does versioning in SharePoint Online? I understand that the last 500 versions are stored, but I didn't find how long these versions are retained by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6080b47a-816c-8bc8-94c0-506d040ae9bd
* Version Independent ID: c06f1880-827d-1d0b-c0fc-601432749411
* Content: [Versioning in SharePoint](https://docs.microsoft.com/en-us/microsoft-365/community/versioning-basics-best-practices)
* Content Source: [Community/versioning-basics-best-practices.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/versioning-basics-best-practices.md)
* Service: **sharepoint-online**
* GitHub Login: @PatD
* Microsoft Alias: **daisyfeller**

**Comment by sympmarc** [comment]
@natlims18 - Versions are stored perpetually unless you decide to delete them. Retention policies you might put in effect can change that default behavior, but out of the box, its the case.
