### ISSUE TITLE
How should organizations decide what to use for org-wide communications?

### ISSUE THREAD

**Issue by sympmarc** [MicrosoftDocs/microsoft-365-community#74]
#### Article suggestion

Tony Redmond did a post about [Microsoft’s Bad Idea to Create an Org-Wide Team for New Office 365 Tenants](https://office365itpros.com/2020/02/29/org-wide-team-small-tenants/)

“Microsoft has announced their intention to create an org-wide team for new small to medium tenants with under 5,000 users. This might help Teams, but it’s a horrible idea on many levels. Microsoft has no idea whether a new tenant wants to use Teams at all, so stuffing Teams down their throat doesn’t seem wise.“

Given that, how should organizations decide what to use for org-wide communications? There are multiple options: an org-wide Team, Yammer, News on the SharePoint home page, email to a DL, etc. What criteria do orgs need to think through to be successful? (Hint: it probably will require some change management.)

**Comment by eemancini** [comment]
I would love to contribute to this one!
