### ISSUE TITLE
Invalid JSON in the "Append to array variable - AttachmentsArray" screenshot

### ISSUE THREAD

**Issue by tgrahampen** [MicrosoftDocs/microsoft-365-community#810]
Hello, you are missing the double quotes around your values in the attachments array variable value screenshot. You have this:

{
  "Name": @{items('Apply_to_each')?['body/{FilenameWithExtension}']},
  "ContentBytes": @{body('Get_file_content')}
}

That's not a valid JSON. It should be this:

{
  "Name": **"**@{items('Apply_to_each')?['body/{FilenameWithExtension}']}**"**,
  "ContentBytes": **"**@{body('Get_file_content')}**"**
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: efceafa2-4c75-9534-5826-8d6f13391c8b
* Version Independent ID: 41bbd300-95aa-6eac-fa8a-dbc735c94102
* Content: [Power Automate - Send SharePoint files as attachments](https://learn.microsoft.com/en-us/microsoft-365/community/power-automate-send-sharepoint-files-as-attachments)
* Content Source: [Community/power-automate-send-sharepoint-files-as-attachments.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/power-automate-send-sharepoint-files-as-attachments.md)
* Service: **power-platform**
* GitHub Login: @JimmyHang
* Microsoft Alias: **daisyfeller**

**Comment by sympmarc** [comment]
@JimmyHang - Want to check this?

**Comment by JimmyHang** [comment]
Hi Marc, I'll have a look..👍

**Comment by JimmyHang** [comment]
Hi @tgrahampen and @sympmarc,

Sorry this has taken some time, anyway I've check the workflow, and it works as it should with the json as above.
To be more specific the append array action, works if the json for file content is like this: **"ContentBytes": @{body('Get_file_content')}**

When I try to add a quote like proposed **"ContentBytes": "@{body('Get_file_content')}"**  the workflows runs, but the resulting file attachment is corrupted.

To be honest I'm not sure why, probably something with how Flow interpret/convert the "file content".

I think you can close this issue now @sympmarc.

Cheers
