### ISSUE TITLE
"Difference" should be "different"

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftDocs/microsoft-365-community#821]
This sentence should use the word "different" instead of "difference": 

This is quite important to work out ahead of time as difference connectors bear a "Premium" or "Enterprise" (in the case of Logic Apps) which affect the overall cost of running the workflow in your decision-making process.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3341b93-944b-b3b4-bdd2-3ef9df2a19d5
* Version Independent ID: 3ecd9b65-0dd5-6f08-b8cf-4766fbb6fa2d
* Content: [Power Automate vs Logic Apps](https://learn.microsoft.com/en-us/microsoft-365/community/power-automate-vs-logic-apps)
* Content Source: [Community/power-automate-vs-logic-apps.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/power-automate-vs-logic-apps.md)
* Service: **power-platform**
* GitHub Login: @pkbullock
* Microsoft Alias: **daisyfeller**

**Comment by sympmarc** [comment]
Sorry for the lag in getting to this, and thanks for the suggestion, @tylerfarmer1. I'll make that change and give you credit for it in the changelog!
