### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by scb3n** [MicrosoftDocs/microsoft-365-community#827]
Typo in header for "iew Formatting" [sic] section, missing "V"
https://learn.microsoft.com/en-us/microsoft-365/community/list-formatting-101#iew-formatting---useful-resources

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 804f03d0-e4ff-5117-9def-3909634c1696
* Version Independent ID: 804f03d0-e4ff-5117-9def-3909634c1696
* Content: [List and Library Formatting](https://learn.microsoft.com/en-us/microsoft-365/community/list-formatting-101)
* Content Source: [Community/list-formatting-101.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/list-formatting-101.md)
* Service: **microsoft-365**
* GitHub Login: @dfrancoeur
* Microsoft Alias: **daisyfeller**

**Comment by sympmarc** [comment]
Thanks for the correction! We'll get that fixed...
