### ISSUE TITLE
Organization chart webpart does not work with "?env=WebView"

### ISSUE THREAD

**Issue by tb1978x** [MicrosoftDocs/microsoft-365-community#832]
![Screenshot 2023-08-02 123816](https://github.com/MicrosoftDocs/microsoft-365-community/assets/141236444/4d703430-6a04-48fb-a7c1-34709b9f2d75)
The org chart webpart displays an error message if the env=WebView querystring parameter is added. The root user is displayed with "[name] cannot be found. Try a different person"

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ac77ab44-dbe6-f6bc-951e-a7e6d44fb8aa
* Version Independent ID: ac77ab44-dbe6-f6bc-951e-a7e6d44fb8aa
* Content: [Query String URL Tricks for SharePoint and Microsoft 365](https://learn.microsoft.com/en-us/microsoft-365/community/query-string-url-tricks-sharepoint-m365)
* Content Source: [Community/query-string-url-tricks-sharepoint-m365.md](https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/query-string-url-tricks-sharepoint-m365.md)
* Service: **sharepoint-online**
* GitHub Login: @PatD
* Microsoft Alias: **daisyfeller**

**Comment by PatD** [comment]
Assign this fix to me please.

**Comment by sympmarc** [comment]
Done! Sorry for the lag.

**Comment by PatD** [comment]
@tb1978x I tested it in my tenant and what I observed was that it shows "[name] cannot be found. Try a different person" for a second... then reloads the page with the org chart.  So maybe it is functionally ok, but an odd user experience.  I'll put a note in on the article about it.  Thanks for calling this one in!

**Comment by tb1978x** [comment]
Hi Patrick

Thanks for looking at my issue. I definitely do not see that behaviour in 3 different tenants - in all cases, the org chart remains in an error state:

[A screenshot of a web page  Description automatically generated]
