### ISSUE TITLE
Microsoft 365 community feedback - 

### ISSUE THREAD

**Issue by DarrellaaS** [MicrosoftDocs/microsoft-365-community#900]
### Type of issue

Routine content update

### Feedback

Loop has changed a lot since this article was published over a year ago. Integration has been established with Planner and To Do. Loop components are now supported in Teams channels. Components are easier to find, appearing in search results, the M365 feed and recently used files. They are easy to share with people beyond the initial conversation if so desired.

### Page URL

https://learn.microsoft.com/en-us/microsoft-365/community/which-task-management-option

### Content source URL

https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/which-task-management-option.md

### Author

@dfrancoeur

### Document Id

74d9a950-4cba-819c-21ec-da1d480d5af8

**Comment by sympmarc** [comment]
@DarrellaaS - Any interest in making updates? I can't think of anyone more knowledgeable!

**Comment by sympmarc** [comment]
@dfrancoeur - Ditto to you.

**Comment by DarrellaaS** [comment]
> @DarrellaaS - Any interest in making updates? I can't think of anyone more knowledgeable!

Sure thing. I can contribute. I haven’t taken the “how to GitHub” course yet. But I’ll figure it out.

**Comment by sympmarc** [comment]
> > @DarrellaaS - Any interest in making updates? I can't think of anyone more knowledgeable!
> 
> Sure thing. I can contribute. I haven’t taken the “how to GitHub” course yet. But I’ll figure it out.

Happy to help you get up to speed if you need it. Ideally you make the changes in a PR here yourself so your name is attached to the article.

**Comment by dfrancoeur** [comment]
I'm happy to help as well 🙂

________________________________
