### ISSUE TITLE
FilterField1 vs FilterFields1

### ISSUE THREAD

**Issue by Leif-Frederiksen** [MicrosoftDocs/microsoft-365-community#931]
### Type of issue

Other (describe below)

### Feedback

As of today it seems like FilterFields1 (plural) is no longer supported. When putting it in the URL, I get the "One or more field types are not installed properly." error. Replacing with the singular "FilterField1" makes things work again, even when filtering on multiple values.
Can you confirm if this is the new behaviour?

### Page URL

https://learn.microsoft.com/en-us/microsoft-365/community/query-string-url-tricks-sharepoint-m365

### Content source URL

https://github.com/MicrosoftDocs/microsoft-365-community/blob/main/Community/query-string-url-tricks-sharepoint-m365.md

### Author

@PatD

### Document Id

ac77ab44-dbe6-f6bc-951e-a7e6d44fb8aa

**Comment by Leif-Frederiksen** [comment]
Error was on my end - sorry for the inconvenience.

**Comment by sympmarc** [comment]
No problem at all. Glad you solved it.
